# Jupyter Notebook for Calculating Statistics

**NOTE**: the `json` files that contain overall metrics and also the linear regression model results were created manually.
This can be done with some Python code very easily. However, the code for this is not included in this notebook.

In [2]:
import pandas as pd
import numpy as np
from math import sqrt
import altair as alt
from utils import save_dataset_to_csv
import statsmodels.formula.api as smf
from tqdm import tqdm
import tiktoken

In [3]:
model_metadata = {
    "alpacare-7B": {"model_type": "biomedical open", "model_size_in_b": 7},
    "biomedgpt7B": {"model_type": "biomedical open", "model_size_in_b": 7},
    "biomistral7B": {"model_type": "biomedical open", "model_size_in_b": 7},
    "claude_3.5-haiku": {"model_type": "generalist closed", "model_size_in_b": None},
    "claude_3.5-sonnet": {"model_type": "generalist closed", "model_size_in_b": None},
    "gemini_1.5_flash": {"model_type": "generalist closed", "model_size_in_b": None},
    "gemini_1.5_flash-8B": {"model_type": "generalist closed", "model_size_in_b": 8},
    "gpt4o": {"model_type": "generalist closed", "model_size_in_b": None},
    "gpt4o-mini": {"model_type": "generalist closed", "model_size_in_b": None},
    "gpt35": {"model_type": "generalist closed", "model_size_in_b": 175},
    "llama2_chat-7B": {"model_type": "generalist open", "model_size_in_b": 7},
    "llama2_chat-13B": {"model_type": "generalist open", "model_size_in_b": 13},
    "llama2_chat-70B": {"model_type": "generalist open", "model_size_in_b": 70},
    "llama3_instruct-8B": {"model_type": "generalist open", "model_size_in_b": 8},
    "llama3_instruct-70B": {"model_type": "generalist open", "model_size_in_b": 70},
    "med42-8B": {"model_type": "biomedical open", "model_size_in_b": 8},
    "med42-70B": {"model_type": "biomedical open", "model_size_in_b": 70},
    "mistral_instruct7B": {"model_type": "generalist open", "model_size_in_b": 7},
    "olmo2_instruct-7B": {"model_type": "generalist open", "model_size_in_b": 7},
    "olmo2_instruct-13B": {"model_type": "generalist open", "model_size_in_b": 13},
    "openbiollm-8B": {"model_type": "biomedical open", "model_size_in_b": 8},
    "openbiollm-70B": {"model_type": "biomedical open", "model_size_in_b": 70}
}

## Spin Detection Task

In [4]:
# detection_overall_metrics.json was manually created
detection_stats_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/detection_overall_metrics_all_new.json", orient="index")

detection_stats_df["model_name"] = detection_stats_df.index
detection_stats_df["model_type"] = detection_stats_df.index.map(lambda x: model_metadata[x]["model_type"])
detection_stats_df["model_size_in_b"] = detection_stats_df.index.map(lambda x: model_metadata[x]["model_size_in_b"])
# remove index
detection_stats_df.reset_index(drop=True, inplace=True)

print(f"Number of models: {len(detection_stats_df)}")

detection_stats_df.sort_index(inplace=True) # alphabetical order
detection_stats_df

Number of models: 22

,accuracy,precision,recall,f1,model_name,model_type,model_size_in_b
0,0.536667,0.537931,0.520000,0.528814,olmo2_instruct-7B,generalist open,7.0
1,0.536667,1.000000,0.073333,0.136646,olmo2_instruct-13B,generalist open,13.0
2,0.500000,0.000000,0.000000,0.000000,mistral_instruct7B,generalist open,7.0
3,0.530000,1.000000,0.060000,0.113208,med42-8B,biomedical open,8.0
4,0.510000,1.000000,0.020000,0.039216,biomistral7B,biomedical open,7.0
5,0.678571,0.678571,1.000000,0.808511,openbiollm-8B,biomedical open,8.0
6,0.500000,0.500000,1.000000,0.666667,llama2_chat-7B,generalist open,7.0
7,0.680000,0.631068,0.866667,0.730337,llama2_chat-13B,generalist open,13.0
8,0.643333,1.000000,0.286667,0.445596,llama3_instruct-8B,generalist open,8.0
9,0.626667,0.593137,0.806667,0.683616,llama2_chat-70B,generalist open,70.0
10,0.610000,1.000000,0.220000,0.360656,llama3_instruct-70B,generalist open,70.0
11,0.583333,0.903226,0.186667,0.309392,med42-70B,biomedical open,70.0
12,0.620000,0.781250,0.333333,0.467290,openbiollm-70B,biomedical open,70.0
13,0.465385,0.468504,0.967480,0.631300,biomedgpt7B,biomedical open,7.0
14,0.500000,0.500000,1.000000,0.666667,alpacare-7B,biomedical open,7.0
15,0.513333,1.000000,0.026667,0.051948,gpt35,generalist closed,175.0
16,0.710000,0.740458,0.646667,0.690391,gpt4o,generalist closed,NaN
17,0.766667,0.750000,0.800000,0.774194,gpt4o-mini,generalist closed,NaN
18,0.676667,0.624413,0.886667,0.732782,gemini_1.5_flash,generalist closed,NaN
19,0.690000,0.851852,0.460000,0.597403,gemini_1.5_flash-8B,generalist closed,8.0
20,0.700000,0.800000,0.533333,0.640000,claude_3.5-sonnet,generalist closed,NaN
21,0.650000,0.601810,0.886667,0.716981,claude_3.5-haiku,generalist closed,NaN

### Average of accuracy by model type

In [5]:
# Group by model type and calculate mean accuracy and standard deviation
accuracy_by_model_type = detection_stats_df.groupby('model_type')['accuracy'].agg(['mean', 'std']).reset_index()

# Rename columns for clarity
accuracy_by_model_type.columns = ['model_type', 'mean_accuracy', 'std_deviation']

print(accuracy_by_model_type)

          model_type  mean_accuracy  std_deviation
0    biomedical open       0.555327       0.075280
1  generalist closed       0.672381       0.078733
2    generalist open       0.579167       0.069322

In [6]:
# Group by model type and calculate mean precision and standard deviation
precision_by_model_type = detection_stats_df.groupby('model_type')['precision'].agg(['mean', 'std']).reset_index()

# Rename columns for clarity
precision_by_model_type.columns = ['model_type', 'mean_precision', 'std_deviation']

print(precision_by_model_type)

          model_type  mean_precision  std_deviation
0    biomedical open        0.761650       0.221866
1  generalist closed        0.766933       0.136131
2    generalist open        0.657767       0.343962

In [7]:
# Group by model type and calculate mean recall and standard deviation
recall_by_model_type = detection_stats_df.groupby('model_type')['recall'].agg(['mean', 'std']).reset_index()

# Rename columns for clarity
recall_by_model_type.columns = ['model_type', 'mean_recall', 'std_deviation']

print(recall_by_model_type)

          model_type  mean_recall  std_deviation
0    biomedical open     0.509640       0.459681
1  generalist closed     0.605714       0.305249
2    generalist open     0.471667       0.383298

In [8]:
# Group by model type and calculate mean f1 and standard deviation
f1_by_model_type = detection_stats_df.groupby('model_type')['f1'].agg(['mean', 'std']).reset_index()

# Rename columns for clarity
f1_by_model_type.columns = ['model_type', 'mean_f1', 'std_deviation']

print(f1_by_model_type)

          model_type   mean_f1  std_deviation
0    biomedical open  0.433655       0.291180
1  generalist closed  0.600528       0.248930
2    generalist open  0.444041       0.265849

#### Plots

In [9]:
# Create a dictionary for custom labels
custom_labels = {
    "alpacare-7B": "AlpaCare 7B",
    "biomedgpt7B": "BioMedGPT 7B",
    "biomistral7B": "BioMistral 7B",
    "claude_3.5-haiku": "Claude3.5 Haiku",
    "claude_3.5-sonnet": "Claude3.5 Sonnet", 
    "gemini_1.5_flash": "Gemini1.5 Flash",
    "gemini_1.5_flash-8B": "Gemini1.5 Flash 8B",
    "gpt4o": "GPT-4o",
    "gpt4o-mini": "GPT-4o Mini",
    "gpt35": "GPT-3.5",
    "llama2_chat-7B": "Llama2 Chat 7B",
    "llama2_chat-13B": "Llama2 Chat 13B",
    "llama2_chat-70B": "Llama2 Chat 70B",
    "llama3_instruct-8B": "Llama3 Instruct 8B",
    "llama3_instruct-70B": "Llama3 Instruct 70B",
    "med42-8B": "Med42 8B",
    "med42-70B": "Med42 70B",
    "mistral_instruct7B": "Mistral Instruct 7B",
    "olmo2_instruct-7B": "Olmo2 Instruct 7B",
    "olmo2_instruct-13B": "Olmo2 Instruct 13B",
    "openbiollm-8B": "OpenBioLLM 8B",
    "openbiollm-70B": "OpenBioLLM 70B"
}

detection_stats_df['model_name_custom'] = detection_stats_df['model_name'].map(custom_labels)

color_mapping = {
    'biomedical open': '#0868ac', 
    'generalist closed': '#7bccc4',
    'generalist open': '#bae4bc',
}

# Create the bar chart
chart = alt.Chart(detection_stats_df).mark_bar().encode(
    y=alt.Y('model_name_custom:N', sort='-x', title='Model Name'),
    x=alt.X('accuracy:Q', title='Accuracy'),
    color=alt.Color('model_type:N', title='Model Type',
                    scale=alt.Scale(domain=list(color_mapping.keys()), range=list(color_mapping.values())),
                    legend=alt.Legend(
                    orient='none',
                    legendX=130, legendY=-45,
                    direction='horizontal',
                    titleAnchor='middle'))  # Legend at the bottom
).properties(
    width=800,
)

# Add value labels with increased font size
text = chart.mark_text(
    align='center',
    baseline='middle',
    fontWeight='bold',
    dx=20  # Adjust the position of the text
).encode(
    text=alt.Text('accuracy:Q', format='.2f'),
    color=alt.value('black'),
)

# Add a mean rule
avg_rule = alt.Chart(detection_stats_df).mark_rule(color='red').encode(
    x='mean(accuracy):Q',
    size=alt.value(2)
)

# Add a 50% chance rule
chance_rule = alt.Chart(detection_stats_df).mark_rule(color='gray').encode(
    x='min(accuracy):Q',
    size=alt.value(2),
    strokeDash=alt.value([10, 10])
)

# Increase font size for axis labels, titles, and other components
chart_config = {
    "axis": {"labelFontSize": 20, "titleFontSize": 22},  # Axis labels and titles
    "header": {"labelFontSize": 20, "titleFontSize": 22},  # Title and facet headers (if any)
    "legend": {"labelFontSize": 18, "titleFontSize": 20},  # Legend labels and titles
    "text": {"fontSize": 20},  # Text mark size
}

# Combine chart and text, and apply the config
c_t = chart + avg_rule + chance_rule + text
c_t = c_t.configure(**chart_config)  # Apply the global configuration

# Save to HTML
c_t.save("./plots/detection_accuracy_by_model.html")

# Display the chart
c_t

alt.LayerChart(...)

In [9]:
# # Create the bar chart
# chart = alt.Chart(detection_stats_df).mark_bar().encode(
#     y=alt.Y('model_name_custom:N', sort='-x', title='Model Name'),
#     x=alt.X('accuracy:Q', title='Accuracy'),
#    color=alt.Color('model_type:N', title='Model Type', legend=alt.Legend(
#         orient='none',
#         legendX=130, legendY=-45,
#         direction='horizontal',
#         titleAnchor='middle'), scale=alt.Scale(range=["#808080", "#A9A9A9", "#D3D3D3", "#BEBEBE"]))  # Legend at the bottom
# ).properties(
#     width=800,
# )

# # Add value labels with increased font size
# text = chart.mark_text(
#     align='center',
#     baseline='middle',
#     fontWeight='bold',
#     dx=18  # Adjust the position of the text
# ).encode(
#     text=alt.Text('accuracy:Q', format='.2f'),
#     color=alt.value('black')  # Set text color to black
# )

# # Add a mean rule
# rule = alt.Chart(detection_stats_df).mark_rule(color='gray').encode(
#     x='mean(accuracy):Q',
#     size=alt.value(2)
# )

# # Increase font size for axis labels, titles, and other components
# chart_config = {
#     "axis": {"labelFontSize": 20, "titleFontSize": 22},  # Axis labels and titles
#     "header": {"labelFontSize": 20, "titleFontSize": 22},  # Title and facet headers (if any)
#     "legend": {"labelFontSize": 18, "titleFontSize": 20},  # Legend labels and titles
#     "text": {"fontSize": 20},  # Text mark size
# }

# # Combine chart and text, and apply the config
# c_t = chart + rule + text
# c_t = c_t.configure(**chart_config)  # Apply the global configuration

# # Save to HTML
# c_t.save("./plots/detection_accuracy_by_model_gray.html")

# # Display the chart
# c_t

In [21]:
# Plot average accuracy by model_type and add error bars
bars = alt.Chart(detection_stats_df).mark_bar().encode(
    x=alt.X('model_type:N', title='Model Type', axis=alt.Axis(labelAngle=0)),
    y=alt.Y('mean(accuracy):Q', title='Mean Accuracy'),
    color=alt.Color('model_type:N', title='Model Type', legend=None)
).properties(
    title='Average Accuracy by Model Type',
    width=800  # Set the width to 800 pixels
)

error_bars = alt.Chart(detection_stats_df).mark_errorbar(extent='stdev').encode(
    x=alt.X('model_type:N'),
    y=alt.Y('accuracy:Q')
)

# Add value labels
text = bars.mark_text(
    align='center',
    baseline='bottom',
    dy=-5  # Adjust the position of the text
).encode(
    text=alt.Text('mean(accuracy):Q', format='.2f')
)

plot_ = alt.layer(bars, error_bars, text)

plot_.save("./plots/average_accuracy_by_model_type.html")

plot_

alt.LayerChart(...)

### Average of accuracy by model size

In [10]:
# model size in buckets (0-10B, 11-20B, 22-100B, 100B+/NaN)
def model_size_bucket(model_size): 
    if model_size is None or pd.isna(model_size):
        return "Unknown"
    elif model_size >= 100:
        return "100B+"
    elif model_size <= 10:
        return "0-10B"
    elif model_size <= 20:
        return "11-20B"
    else:
        return "21-100B"

In [11]:
# average accuracy by model size
detection_stats_df["model_size_bucket"] = detection_stats_df["model_size_in_b"].map(model_size_bucket)

accuracy_by_model_size = detection_stats_df.groupby('model_size_bucket')['accuracy'].agg(['mean', 'std']).reset_index()

# Rename columns for clarity
accuracy_by_model_size.columns = ['model_size_bucket', 'mean_accuracy', 'std_deviation']

print(accuracy_by_model_size)

  model_size_bucket  mean_accuracy  std_deviation
0             0-10B       0.555396       0.082589
1             100B+       0.513333            NaN
2            11-20B       0.608333       0.101352
3           21-100B       0.610000       0.019052
4           Unknown       0.700667       0.043551

In [12]:
# average precision by model size
precision_by_model_size = detection_stats_df.groupby('model_size_bucket')['precision'].agg(['mean', 'std']).reset_index()

# Rename columns for clarity
precision_by_model_size.columns = ['model_size_bucket', 'mean_precision', 'std_deviation']

print(precision_by_model_size)

  model_size_bucket  mean_precision  std_deviation
0             0-10B        0.653686       0.320056
1             100B+        1.000000            NaN
2            11-20B        0.815534       0.260874
3           21-100B        0.819403       0.175398
4           Unknown        0.703336       0.085784

In [13]:
# average recall by model size
recall_by_model_size = detection_stats_df.groupby('model_size_bucket')['recall'].agg(['mean', 'std']).reset_index()

# Rename columns for clarity
recall_by_model_size.columns = ['model_size_bucket', 'mean_recall', 'std_deviation']

print(recall_by_model_size)

  model_size_bucket  mean_recall  std_deviation
0             0-10B     0.531415       0.432072
1             100B+     0.026667            NaN
2            11-20B     0.470000       0.560971
3           21-100B     0.386667       0.286951
4           Unknown     0.750667       0.156105

In [14]:
# average f1 score by model size 
f1_by_model_size_bucket = detection_stats_df.groupby('model_size_bucket')['f1'].agg(['mean', 'std']).reset_index()

# Rename columns for clarity
f1_by_model_size_bucket.columns = ['model_size_bucket', 'mean_f1', 'std_deviation']

print(f1_by_model_size_bucket)

  model_size_bucket   mean_f1  std_deviation
0             0-10B  0.449738       0.292103
1             100B+  0.051948            NaN
2            11-20B  0.433492       0.419803
3           21-100B  0.455238       0.165850
4           Unknown  0.710870       0.049923

#### Plots

In [22]:
bars = alt.Chart(detection_stats_df).mark_bar().encode(
    x=alt.X('model_name:N', sort='-y', title='Model Name'),
    y=alt.Y('accuracy:Q', title='Accuracy'),
    color=alt.Color('model_size_bucket:N', title='Model Size Bucket')
).properties(
    title='Accuracy by Model Size Bucket',
    width=800,
)

# Add value labels
text = bars.mark_text(
    align='center',
    baseline='bottom',
    dy=-5  # Adjust the position of the text
).encode(
    text=alt.Text('accuracy:Q', format='.2f')
)

plot_ = bars + text

plot_.save("./plots/average_accuracy_by_model_size.html")

plot_

alt.LayerChart(...)

In [23]:
# Plot average accuracy by model_size_bucket and add error bars
bars = alt.Chart(detection_stats_df).mark_bar().encode(
    x=alt.X('model_size_bucket:N', title='Model Size Bucket', axis=alt.Axis(labelAngle=0), sort=['0-10B', '11-20B', '21-100B', '100B+', 'Unknown']),
    y=alt.Y('mean(accuracy):Q', title='Mean Accuracy'),
    color=alt.Color('model_size_bucket:N', title='Model Size Bucket', legend=None)
).properties(
    title='Average Accuracy by Model Size',
    width=800  # Set the width to 800 pixels
)

error_bars = alt.Chart(detection_stats_df).mark_errorbar(extent='stdev').encode(
    x=alt.X('model_size_bucket:N', sort=['0-10B', '11-20B', '21-100B', '100B+', 'Unknown']),
    y=alt.Y('accuracy:Q')
)

# Add value labels
text = bars.mark_text(
    align='center',
    baseline='bottom',
    dy=-5  # Adjust the position of the text
).encode(
    text=alt.Text('mean(accuracy):Q', format='.2f')
)

plot_ = alt.layer(bars, error_bars, text)

plot_.save("./plots/average_accuracy_by_model_size_bucket.html")

plot_

alt.LayerChart(...)

In [24]:
# scatter plot of model size vs accuracy with model names as labels
scatter_plot = alt.Chart(detection_stats_df).mark_circle().encode(
    x=alt.X('model_size_in_b:Q', title='Model Size (in Billion Parameters)'),
    y=alt.Y('accuracy:Q', title='Accuracy'),
    color=alt.Color('model_type:N', title='Model Type')
).properties(
    title='Model Size vs Accuracy',
    width=800,  # Set the width to 800 pixels
    height=400  # Set the height to 400 pixels
)

text = scatter_plot.mark_text(
    align='left',
    baseline='middle',
    dx=7,  # Adjust the position of the text
    dy=-5,  # Adjust the vertical position of the text
).encode(
    text='model_name:N'
)

plot_ = scatter_plot + text

plot_.save("./plots/model_size_vs_accuracy.html")

plot_

alt.LayerChart(...)

## RCT Trial Result Interpretation Task

In [25]:
# interpretation_overall_metrics.json was manually created
interpretation_stats_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/interpretation_overall_metrics_all_new.json", orient="index")

interpretation_stats_df["model_name"] = interpretation_stats_df.index
interpretation_stats_df["model_type"] = interpretation_stats_df.index.map(lambda x: model_metadata[x]["model_type"])
interpretation_stats_df["model_size_in_b"] = interpretation_stats_df.index.map(lambda x: model_metadata[x]["model_size_in_b"])
# remove index
interpretation_stats_df.reset_index(drop=True, inplace=True)

print(f"Number of models: {len(interpretation_stats_df)}")

interpretation_stats_df.sort_index(inplace=True) # alphabetical order
interpretation_stats_df

Number of models: 22

,benefit_answer_mean_diff,rigor_answer_mean_diff,importance_answer_mean_diff,full_text_answer_mean_diff,another_trial_answer_mean_diff,overall_mean_diff_avg,model_name,model_type,model_size_in_b
0,3.377778,0.420000,1.100000,2.160000,1.573333,1.726222,olmo2_instruct-7B,generalist open,7.0
1,2.946667,0.766667,1.753333,3.013333,2.440000,2.184000,olmo2_instruct-13B,generalist open,13.0
2,1.766667,0.046667,1.620000,1.580000,1.253333,1.253333,mistral_instruct7B,generalist open,7.0
3,2.226667,0.240000,0.933333,1.120000,1.653333,1.234667,med42-8B,biomedical open,8.0
4,0.626667,0.026667,0.786667,0.547619,0.496667,0.496857,biomistral7B,biomedical open,7.0
5,3.401575,-0.062500,2.900000,4.420635,0.909091,2.313760,openbiollm-8B,biomedical open,8.0
6,1.663194,0.160000,0.966667,0.260000,-0.035398,0.602893,llama2_chat-7B,generalist open,7.0
7,2.402027,0.300000,1.193333,1.600000,1.506667,1.400405,llama2_chat-13B,generalist open,13.0
8,1.686667,0.066667,0.673333,0.880000,1.253333,0.912000,llama3_instruct-8B,generalist open,8.0
9,1.672932,0.126667,0.586667,0.513333,0.398551,0.659630,llama2_chat-70B,generalist open,70.0
10,2.640000,0.040000,0.760000,1.646667,2.053333,1.428000,llama3_instruct-70B,generalist open,70.0
11,3.180702,0.000000,0.600000,2.328767,2.610738,1.744041,med42-70B,biomedical open,70.0
12,3.428667,-0.003333,0.696644,0.804348,1.566667,1.298598,openbiollm-70B,biomedical open,70.0
13,0.257426,-0.272727,0.000000,NaN,0.000000,NaN,biomedgpt7B,biomedical open,7.0
14,-0.375000,-0.020000,-2.285714,0.116667,0.860000,-0.340810,alpacare-7B,biomedical open,7.0
15,2.646667,0.360000,1.000000,1.233333,1.446667,1.337333,gpt35,generalist closed,175.0
16,1.753333,0.146667,0.520000,1.526667,1.486667,1.086667,gpt4o,generalist closed,NaN
17,2.306667,0.646667,1.500000,2.526667,2.146667,1.825333,gpt4o-mini,generalist closed,NaN
18,1.940000,0.060000,1.093333,1.840000,1.740000,1.334667,gemini_1.5_flash,generalist closed,NaN
19,1.593333,-0.100000,0.806667,2.113333,1.580000,1.198667,gemini_1.5_flash-8B,generalist closed,8.0
20,1.000000,0.000000,-0.333333,0.333333,1.000000,0.400000,claude_3.5-sonnet,generalist closed,NaN
21,1.666667,0.000000,0.333333,0.333333,1.666667,0.800000,claude_3.5-haiku,generalist closed,NaN

In [26]:
human_expert_stats = {
        "benefit_answer": {"mean_diff": 0.71, "ci_lower": 0.07, "ci_upper": 1.35},
        "rigor_answer": {"mean_diff": -0.59, "ci_lower": -1.13, "ci_upper": -0.05},
        "importance_answer": {"mean_diff": -0.38, "ci_lower": -0.95, "ci_upper": 0.19},
        "full_text_answer": {"mean_diff": 0.77, "ci_lower": 0.08, "ci_upper": 1.47},
        "another_trial_answer": {"mean_diff": 0.64, "ci_lower": -0.03, "ci_upper": 1.31}
    }

human_expert_stats_df = pd.DataFrame(human_expert_stats).T
human_expert_stats_df["metric"] = human_expert_stats_df.index
# remove index
human_expert_stats_df.reset_index(drop=True, inplace=True)
human_expert_stats_df["method"] = "human experts"

human_expert_stats_df

   mean_diff  ci_lower  ci_upper                metric         method
0       0.71      0.07      1.35        benefit_answer  human experts
1      -0.59     -1.13     -0.05          rigor_answer  human experts
2      -0.38     -0.95      0.19     importance_answer  human experts
3       0.77      0.08      1.47      full_text_answer  human experts
4       0.64     -0.03      1.31  another_trial_answer  human experts

In [10]:
def calculate_confidence_interval(df, df_column_name):
    mean_diff = df[df_column_name].mean()  # Calculate the mean
    std_dev = df[df_column_name].std()  # Calculate the standard deviation
    n = len(df[df_column_name])  # Sample size

    # Calculate the margin of error for 95% CI (z = 1.96)
    z = 1.96
    margin_of_error = z * (std_dev / sqrt(n))

    # Calculate the 95% Confidence Interval
    ci_lower = mean_diff - margin_of_error
    ci_upper = mean_diff + margin_of_error

    return ci_lower, ci_upper

In [11]:
def calculate_model_stats(interpretation_stats_df, method_name = "all LLMs"):
    # calculate the average of all model metrics and calculate 95% CI
    average_model_benefit = interpretation_stats_df["benefit_answer_mean_diff"].mean()
    ci_lower_model_benefit, ci_upper_model_benefit = calculate_confidence_interval(interpretation_stats_df, "benefit_answer_mean_diff")

    average_model_rigor = interpretation_stats_df["rigor_answer_mean_diff"].mean()
    ci_lower_model_rigor, ci_upper_model_rigor = calculate_confidence_interval(interpretation_stats_df, "rigor_answer_mean_diff")

    average_model_importance = interpretation_stats_df["importance_answer_mean_diff"].mean()
    ci_lower_model_importance, ci_upper_model_importance = calculate_confidence_interval(interpretation_stats_df, "importance_answer_mean_diff")

    average_model_full_text = interpretation_stats_df["full_text_answer_mean_diff"].mean()
    ci_lower_model_full_text, ci_upper_model_full_text = calculate_confidence_interval(interpretation_stats_df, "full_text_answer_mean_diff")

    average_model_another_trial = interpretation_stats_df["another_trial_answer_mean_diff"].mean()
    ci_lower_model_another_trial, ci_upper_model_another_trial = calculate_confidence_interval(interpretation_stats_df, "another_trial_answer_mean_diff")

    model_stats = {
        "benefit_answer": {"mean_diff": average_model_benefit, "ci_lower": ci_lower_model_benefit, "ci_upper": ci_upper_model_benefit},
        "rigor_answer": {"mean_diff": average_model_rigor, "ci_lower": ci_lower_model_rigor, "ci_upper": ci_upper_model_rigor},
        "importance_answer": {"mean_diff": average_model_importance, "ci_lower": ci_lower_model_importance, "ci_upper": ci_upper_model_importance},
        "full_text_answer": {"mean_diff": average_model_full_text, "ci_lower": ci_lower_model_full_text, "ci_upper": ci_upper_model_full_text},
        "another_trial_answer": {"mean_diff": average_model_another_trial, "ci_lower": ci_lower_model_another_trial, "ci_upper": ci_upper_model_another_trial}
    }

    model_stats_df = pd.DataFrame(model_stats).T
    model_stats_df["metric"] = model_stats_df.index
    # remove index
    model_stats_df.reset_index(drop=True, inplace=True)
    model_stats_df["method"] = method_name

    return model_stats_df

In [29]:
# calculate the average of all model metrics and calculate 95% CI
model_stats_df = calculate_model_stats(interpretation_stats_df)

model_stats_df

   mean_diff  ci_lower  ci_upper                metric    method
0   1.991332  1.567488  2.415176        benefit_answer  all LLMs
1   0.134005  0.032919  0.235091          rigor_answer  all LLMs
2   0.782012  0.387193  1.176831     importance_answer  all LLMs
3   1.471335  1.026661  1.916010      full_text_answer  all LLMs
4   1.345742  1.051612  1.639871  another_trial_answer  all LLMs

In [30]:
# get average and 95% CI by model_type from interpretation_stats_df for each model_type
interpretation_stats_df["model_type"] = interpretation_stats_df["model_name"].map(lambda x: model_metadata[x]["model_type"])

# get only generalist closed  models
generalist_closed_model_stats = interpretation_stats_df[interpretation_stats_df["model_type"] == "generalist closed"]

# get only generalist open models
generalist_open_model_stats = interpretation_stats_df[interpretation_stats_df["model_type"] == "generalist open"]

# get only biomedical open models
biomedical_open_model_stats = interpretation_stats_df[interpretation_stats_df["model_type"] == "biomedical open"]

In [31]:
generalist_closed_model_stats_df = calculate_model_stats(generalist_closed_model_stats, method_name = "generalist closed")

generalist_open_model_stats_df = calculate_model_stats(generalist_open_model_stats, method_name = "generalist open")

biomedical_open_model_stats_df = calculate_model_stats(biomedical_open_model_stats, method_name = "biomedical open")

In [32]:
generalist_closed_model_stats_df

   mean_diff  ci_lower  ci_upper                metric             method
0   1.843810  1.451531  2.236088        benefit_answer  generalist closed
1   0.159048 -0.033614  0.351710          rigor_answer  generalist closed
2   0.702857  0.261401  1.144314     importance_answer  generalist closed
3   1.415238  0.788857  2.041619      full_text_answer  generalist closed
4   1.580952  1.324845  1.837060  another_trial_answer  generalist closed

In [33]:
generalist_open_model_stats_df

   mean_diff  ci_lower  ci_upper                metric           method
0   2.269491  1.804069  2.734914        benefit_answer  generalist open
1   0.240833  0.067090  0.414576          rigor_answer  generalist open
2   1.081667  0.785088  1.378245     importance_answer  generalist open
3   1.456667  0.834420  2.078913      full_text_answer  generalist open
4   1.305394  0.744591  1.866198  another_trial_answer  generalist open

In [34]:
biomedical_open_model_stats_df

   mean_diff  ci_lower  ci_upper                metric           method
0   1.820957  0.619193  3.022722        benefit_answer  biomedical open
1  -0.013128 -0.124579  0.098324          rigor_answer  biomedical open
2   0.518704 -0.616388  1.653796     importance_answer  biomedical open
3   1.556339  0.378153  2.734525      full_text_answer  biomedical open
4   1.156642  0.518521  1.794764  another_trial_answer  biomedical open

In [35]:
average_by_model_type = pd.concat([generalist_open_model_stats_df, biomedical_open_model_stats_df, generalist_closed_model_stats_df], ignore_index=True)

average_by_model_type

    mean_diff  ci_lower  ci_upper                metric             method
0    2.269491  1.804069  2.734914        benefit_answer    generalist open
1    0.240833  0.067090  0.414576          rigor_answer    generalist open
2    1.081667  0.785088  1.378245     importance_answer    generalist open
3    1.456667  0.834420  2.078913      full_text_answer    generalist open
4    1.305394  0.744591  1.866198  another_trial_answer    generalist open
5    1.820957  0.619193  3.022722        benefit_answer    biomedical open
6   -0.013128 -0.124579  0.098324          rigor_answer    biomedical open
7    0.518704 -0.616388  1.653796     importance_answer    biomedical open
8    1.556339  0.378153  2.734525      full_text_answer    biomedical open
9    1.156642  0.518521  1.794764  another_trial_answer    biomedical open
10   1.843810  1.451531  2.236088        benefit_answer  generalist closed
11   0.159048 -0.033614  0.351710          rigor_answer  generalist closed
12   0.702857  0.261401  1.144314     importance_answer  generalist closed
13   1.415238  0.788857  2.041619      full_text_answer  generalist closed
14   1.580952  1.324845  1.837060  another_trial_answer  generalist closed

In [36]:
#combine all the dataframes
model_stats_final_df = pd.concat([human_expert_stats_df, model_stats_df, average_by_model_type], ignore_index=True)
#drop "_answer" from the values in metric column
model_stats_final_df['metric'] = model_stats_final_df['metric'].str.replace('_answer', '')

model_stats_final_df

    mean_diff  ci_lower  ci_upper         metric             method
0    0.710000  0.070000  1.350000        benefit      human experts
1   -0.590000 -1.130000 -0.050000          rigor      human experts
2   -0.380000 -0.950000  0.190000     importance      human experts
3    0.770000  0.080000  1.470000      full_text      human experts
4    0.640000 -0.030000  1.310000  another_trial      human experts
5    1.991332  1.567488  2.415176        benefit           all LLMs
6    0.134005  0.032919  0.235091          rigor           all LLMs
7    0.782012  0.387193  1.176831     importance           all LLMs
8    1.471335  1.026661  1.916010      full_text           all LLMs
9    1.345742  1.051612  1.639871  another_trial           all LLMs
10   2.269491  1.804069  2.734914        benefit    generalist open
11   0.240833  0.067090  0.414576          rigor    generalist open
12   1.081667  0.785088  1.378245     importance    generalist open
13   1.456667  0.834420  2.078913      full_text    generalist open
14   1.305394  0.744591  1.866198  another_trial    generalist open
15   1.820957  0.619193  3.022722        benefit    biomedical open
16  -0.013128 -0.124579  0.098324          rigor    biomedical open
17   0.518704 -0.616388  1.653796     importance    biomedical open
18   1.556339  0.378153  2.734525      full_text    biomedical open
19   1.156642  0.518521  1.794764  another_trial    biomedical open
20   1.843810  1.451531  2.236088        benefit  generalist closed
21   0.159048 -0.033614  0.351710          rigor  generalist closed
22   0.702857  0.261401  1.144314     importance  generalist closed
23   1.415238  0.788857  2.041619      full_text  generalist closed
24   1.580952  1.324845  1.837060  another_trial  generalist closed

### Plots

In [37]:
# Create a mapping for custom facet titles
facet_title_mapping = {
    'benefit': 'Treatment Benefit',
    'rigor': 'Study Rigor',
    'importance': 'Study Importance',
    'full_text': 'Interest to Read Full-Text',
    'another_trial': 'Interest to Run Another Trial'
}

# Define the desired order for the facets
facet_order = ['Treatment Benefit', 'Study Rigor', 'Study Importance', 'Interest to Read Full-Text', 'Interest to Run Another Trial']

color_mapping = {
    'human experts': '#0868ac', 
    'all LLMs': '#43a2ca',  
    'generalist closed': '#7bccc4',  
    'generalist open': '#bae4bc',  
    'biomedical open': '#E3F4D4'
}

method_order = ['human experts', 'all LLMs', 'generalist closed', 'generalist open', 'biomedical open']

# Apply the mapping as a calculated field
chart_data = model_stats_final_df.copy()
chart_data['metric'] = chart_data['metric'].map(facet_title_mapping)

# Configure global font sizes
chart_config = {
    "axis": {"labelFontSize": 20, "titleFontSize": 22},  # Axis labels and titles
    "header": {"labelFontSize": 20, "titleFontSize": 22},  # Facet headers
    "legend": {"labelFontSize": 18, "titleFontSize": 20},  # Legend labels and titles
    "text": {"fontSize": 20},  # Text mark size
}

# Bar chart
bars = alt.Chart(chart_data).mark_bar().encode(
    x=alt.X('method:N', title=None, axis=alt.Axis(labelAngle=-45), sort=method_order),
    y=alt.Y('mean_diff:Q', title='Mean Difference'),
    color=alt.Color('method:N', title='Method', legend=None, scale=alt.Scale(domain=list(color_mapping.keys()), range=list(color_mapping.values())))
).properties(
    width=300,  # Set the width to 300 pixels
    height=300  # Set the height to 300 pixels
)

# Error bars
error_bars = alt.Chart(chart_data).mark_errorbar().encode(
    alt.X("method:N", sort=method_order),
    alt.Y("ci_lower:Q").title("Mean Difference"),
    alt.Y2("ci_upper:Q"),
    strokeWidth=alt.value(2),
    color=alt.value('gray')
)

# Add value labels
text = bars.mark_text(
    align='center',
    baseline='bottom',
    fontWeight='bold',
    dy=alt.expr(expr=alt.expr.if_(alt.datum.mean_diff >= 0, -1, 20))  # Adjust the position of the text    
).encode(
    text=alt.Text('mean_diff:Q', format='.2f'),
    color=alt.value('black')  # Set text color to black
)

# Combine layers and facet
chart = alt.layer(bars, error_bars, text, data=chart_data).facet(
    column=alt.Column('metric:N', title=None, sort=facet_order),
).configure(**chart_config)  # Apply the global configuration

# save to html
chart.save("./plots/interpretation_by_measures.html")

chart

alt.FacetChart(...)

In [38]:
# same plot as above but for only top-6 spin detection accuracy models compare in regards to interpretation

claude_sonnet_diff_data = "eval_outputs/claude_3.5-sonnet/claude_3.5-sonnet_interpretation_outputs.json"
gpt4o_mini_diff_data = "eval_outputs/gpt4o-mini/gpt4o-mini_interpretation_outputs.json"
gemini_flash_8b_diff_data = "eval_outputs/gemini_1.5_flash-8B/gemini_1.5_flash-8B_interpretation_outputs.json"
llama3_8b_diff_data = "eval_outputs/llama3_instruct-8B/llama3_instruct-8B_interpretation_outputs.json"
llama3_70b_diff_data = "eval_outputs/llama3_instruct-70B/llama3_instruct-70B_interpretation_outputs.json"
openbiollm_70b_diff_data = "eval_outputs/openbiollm-70B/openbiollm-70B_interpretation_outputs.json"

# read all the data
claude_sonnet_data = pd.read_json(claude_sonnet_diff_data, orient="record")
gpt4o_mini_data = pd.read_json(gpt4o_mini_diff_data, orient="record")
gemini_flash_8b_data = pd.read_json(gemini_flash_8b_diff_data, orient="record")
llama3_8b_data = pd.read_json(llama3_8b_diff_data, orient="record")
llama3_70b_data = pd.read_json(llama3_70b_diff_data, orient="record")
openbiollm_70b_data = pd.read_json(openbiollm_70b_diff_data, orient="record")

def calculate_ci(data):
    mean_diff = np.mean(data)  # Calculate the mean
    std_dev = np.std(data, ddof=1)  # Use ddof=1 for sample standard deviation  # Calculate the standard deviation
    n = len(data)  # Sample size

    # Calculate the margin of error for 95% CI (z = 1.96)
    z = 1.96
    margin_of_error = z * (std_dev / sqrt(n))

    # Calculate the 95% Confidence Interval
    ci_lower = mean_diff - margin_of_error
    ci_upper = mean_diff + margin_of_error

    return ci_lower, ci_upper

def get_metrics(df):
    column_names = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer"]
    
    diff_metrics = []
    
    for col in column_names:
        df_copy = df.copy()
        
        # Remove rows where the column has 'Error' or empty string
        mask = df_copy[col].apply(lambda x: isinstance(x, str) and ("Error" in x or x == ""))
        if mask.any():
            error_pmids = df_copy.loc[mask, 'PMID'].unique().tolist()
            print(f"Column '{col}' has some 'Error' or empty string values. Removing these rows...")
            print(f"PMIDs with errors: {error_pmids}")
            df_copy = df_copy[~df_copy['PMID'].isin(error_pmids)]
            print(f"Remaining rows after cleanup: {len(df_copy)}")
        
        # Ensure the column is converted to numeric, coercing errors
        df_copy[col] = pd.to_numeric(df_copy[col], errors='coerce')

        # For each group by PMID, get the column values difference (abstract_type == spin minus abstract_type == non-spin)
        grouped = df_copy.pivot_table(index='PMID', columns='abstract_type', values=col, aggfunc='mean')
        diff = grouped['spin'] - grouped['no_spin']
        diffs = diff.tolist()

        # calculate confidence interval
        ci_lower, ci_upper = calculate_ci(diffs)

        diff_metrics.append({
            "metric": col,
            "mean_diff": diff.mean(),
            "ci_lower": ci_lower,
            "ci_upper": ci_upper
        })

    return diff_metrics


# get metrics for each model
# save to dataframe for each model
model_data = {
    "Claude 3.5 Sonnet": claude_sonnet_data,
    "GPT4o Mini": gpt4o_mini_data,
    "Gemini1.5 Flash 8B": gemini_flash_8b_data,
    "Llama3 8B": llama3_8b_data,
    "Llama3 70B": llama3_70b_data,
    "OpenBioLLM 70B": openbiollm_70b_data
}
df_for_chart = pd.DataFrame()
for model_name, df in model_data.items():
    diff_metrics = get_metrics(df)
    # create a dataframe
    df_model = pd.DataFrame(diff_metrics)
    df_model["method"] = model_name
    df_for_chart = pd.concat([df_for_chart, df_model], ignore_index=True)

df_for_chart = pd.concat([df_for_chart, human_expert_stats_df], ignore_index=True)
#drop "_answer" from the values in metric column
df_for_chart['metric'] = df_for_chart['metric'].str.replace('_answer', '')

df_for_chart

Column 'full_text_answer' has some 'Error' or empty string values. Removing these rows...
PMIDs with errors: [11261827, 12177098, 15947110, 16148021, 16314619, 17179098, 18794551, 20087643, 20530276, 21471562, 22112969, 9093724]
Remaining rows after cleanup: 36

           metric  mean_diff  ci_lower  ci_upper              method
0         benefit   2.500000  1.978884  3.021116   Claude 3.5 Sonnet
1           rigor  -0.166667 -0.302308 -0.031026   Claude 3.5 Sonnet
2      importance  -0.633333 -0.872616 -0.394051   Claude 3.5 Sonnet
3       full_text   3.233333  2.679892  3.786775   Claude 3.5 Sonnet
4   another_trial   2.866667  2.210635  3.522698   Claude 3.5 Sonnet
5         benefit   3.566667  2.989786  4.143547          GPT4o Mini
6           rigor   1.466667  1.118410  1.814923          GPT4o Mini
7      importance   2.733333  2.283300  3.183367          GPT4o Mini
8       full_text   3.933333  3.402286  4.464381          GPT4o Mini
9   another_trial   3.866667  3.281804  4.451529          GPT4o Mini
10        benefit   3.066667  2.626554  3.506779  Gemini1.5 Flash 8B
11          rigor  -0.100000 -0.272002  0.072002  Gemini1.5 Flash 8B
12     importance   0.966667  0.692954  1.240379  Gemini1.5 Flash 8B
13      full_text   2.733333  2.177901  3.288766  Gemini1.5 Flash 8B
14  another_trial   3.433333  3.085711  3.780955  Gemini1.5 Flash 8B
15        benefit   2.200000  1.726382  2.673618           Llama3 8B
16          rigor   0.166667  0.001652  0.331681           Llama3 8B
17     importance   0.900000  0.612646  1.187354           Llama3 8B
18      full_text   1.500000  1.082367  1.917633           Llama3 8B
19  another_trial   2.733333  2.283300  3.183367           Llama3 8B
20        benefit   4.400000  3.718440  5.081560          Llama3 70B
21          rigor  -0.033333 -0.098667  0.032000          Llama3 70B
22     importance   0.966667  0.511268  1.422065          Llama3 70B
23      full_text   3.400000  2.847224  3.952776          Llama3 70B
24  another_trial   4.066667  3.321160  4.812174          Llama3 70B
25        benefit   4.400000  3.863438  4.936562      OpenBioLLM 70B
26          rigor   0.000000  0.000000  0.000000      OpenBioLLM 70B
27     importance   0.633333  0.275694  0.990973      OpenBioLLM 70B
28      full_text   1.055556  0.225022  1.886089      OpenBioLLM 70B
29  another_trial   4.933333  4.377901  5.488766      OpenBioLLM 70B
30        benefit   0.710000  0.070000  1.350000       human experts
31          rigor  -0.590000 -1.130000 -0.050000       human experts
32     importance  -0.380000 -0.950000  0.190000       human experts
33      full_text   0.770000  0.080000  1.470000       human experts
34  another_trial   0.640000 -0.030000  1.310000       human experts

In [39]:

# Create a mapping for custom facet titles
facet_title_mapping = {
    'benefit': 'Treatment Benefit',
    'rigor': 'Study Rigor',
    'importance': 'Study Importance',
    'full_text': 'Interest to Read Full-Text',
    'another_trial': 'Interest to Run Another Trial'
}

# Define the desired order for the facets
facet_order = ['Treatment Benefit', 'Study Rigor', 'Study Importance', 'Interest to Read Full-Text', 'Interest to Run Another Trial']

color_mapping = {
    'human experts': '#0868ac', 
    'Claude 3.5 Sonnet': '#43a2ca',  
    'GPT4o Mini': '#7bccc4',  
    'Gemini1.5 Flash 8B': '#bae4bc',  
    'Llama3 8B': '#E3F4D4',  
    'Llama3 70B': '#fdd49e',  
    'OpenBioLLM 70B': '#fdae61'
}

method_order = ['human experts', 'Claude 3.5 Sonnet', 'GPT-4o Mini', 'Gemini1.5 Flash 8B', 'Llama3 8B', 'Llama3 70B', 'OpenBioLLM 70B']

# Apply the mapping as a calculated field
chart_data = df_for_chart.copy()
chart_data['metric'] = chart_data['metric'].map(facet_title_mapping)

# Configure global font sizes
chart_config = {
    "axis": {"labelFontSize": 20, "titleFontSize": 22},  # Axis labels and titles
    "header": {"labelFontSize": 20, "titleFontSize": 22},  # Facet headers
    "legend": {"labelFontSize": 18, "titleFontSize": 20},  # Legend labels and titles
    "text": {"fontSize": 20},  # Text mark size
}

# Bar chart
bars = alt.Chart(chart_data).mark_bar().encode(
    x=alt.X('method:N', title=None, axis=alt.Axis(labelAngle=-45), sort=method_order),
    y=alt.Y('mean_diff:Q', title='Mean Difference'),
    color=alt.Color('method:N', title='Method', legend=None, scale=alt.Scale(domain=list(color_mapping.keys()), range=list(color_mapping.values())))
).properties(
    width=300,  # Set the width to 300 pixels
    height=300  # Set the height to 300 pixels
)

# Error bars
error_bars = alt.Chart(chart_data).mark_errorbar().encode(
    alt.X("method:N", sort=method_order),
    alt.Y("ci_lower:Q").title("Mean Difference"),
    alt.Y2("ci_upper:Q"),
    strokeWidth=alt.value(2),
    color=alt.value('gray')
)

# Add value labels
text = bars.mark_text(
    align='center',
    baseline='bottom',
    fontWeight='bold',
    dy=alt.expr(expr=alt.expr.if_(alt.datum.mean_diff >= 0, -1, 22))  # Adjust the position of the text    
).encode(
    text=alt.Text('mean_diff:Q', format='.2f'),
    color=alt.value('black')  # Set text color to black
)

# Combine layers and facet
chart = alt.layer(bars, error_bars, text, data=chart_data).facet(
    column=alt.Column('metric:N', title=None, sort=facet_order),
).configure(**chart_config)  # Apply the global configuration

# save to html
chart.save("./plots/top_6_models_interpretation_by_measures.html")

chart

alt.FacetChart(...)

### Mitigation Strategies Results

In [40]:
model_stats_df['method'] = 'baseline'

In [41]:
# gold_labelled_interpretation_overall_metrics.json was manually created
gold_labelled_interpretation_stats_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/gold_labelled_interpretation_overall_metrics_all_new.json", orient="index")

gold_labelled_interpretation_stats_df["model_name"] = gold_labelled_interpretation_stats_df.index
gold_labelled_interpretation_stats_df["model_type"] = gold_labelled_interpretation_stats_df.index.map(lambda x: model_metadata[x]["model_type"])
gold_labelled_interpretation_stats_df["model_size_in_b"] = gold_labelled_interpretation_stats_df.index.map(lambda x: model_metadata[x]["model_size_in_b"])
# remove index
gold_labelled_interpretation_stats_df.reset_index(drop=True, inplace=True)

print(f"Number of models: {len(gold_labelled_interpretation_stats_df)}")

gold_labelled_interpretation_stats_df.sort_index(inplace=True) # alphabetical order

Number of models: 22

In [42]:
# calculate the average of all model metrics and calculate 95% CI
gold_labelled_model_stats_df = calculate_model_stats(gold_labelled_interpretation_stats_df, method_name = "+ ref labels")
gold_labelled_model_stats_df

   mean_diff  ci_lower  ci_upper                metric        method
0   1.046383  0.677622  1.415144        benefit_answer  + ref labels
1  -1.066753 -1.419150 -0.714357          rigor_answer  + ref labels
2  -0.447535 -0.731092 -0.163978     importance_answer  + ref labels
3  -0.192852 -0.670337  0.284633      full_text_answer  + ref labels
4   0.341208  0.019668  0.662749  another_trial_answer  + ref labels

In [43]:
# model_output_labelled_interpretation_overall_metrics.json was manually created
model_output_labelled_interpretation_stats_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/model_output_labelled_interpretation_overall_metrics_all_new.json", orient="index")

model_output_labelled_interpretation_stats_df["model_name"] = model_output_labelled_interpretation_stats_df.index
model_output_labelled_interpretation_stats_df["model_type"] = model_output_labelled_interpretation_stats_df.index.map(lambda x: model_metadata[x]["model_type"])
model_output_labelled_interpretation_stats_df["model_size_in_b"] = model_output_labelled_interpretation_stats_df.index.map(lambda x: model_metadata[x]["model_size_in_b"])
# remove index
model_output_labelled_interpretation_stats_df.reset_index(drop=True, inplace=True)

print(f"Number of models: {len(model_output_labelled_interpretation_stats_df)}")

model_output_labelled_interpretation_stats_df.sort_index(inplace=True) # alphabetical order

Number of models: 22

In [44]:
# calculate the average of all model metrics and calculate 95% CI
model_output_labelled_model_stats_df = calculate_model_stats(model_output_labelled_interpretation_stats_df, method_name = "+ model labels")
model_output_labelled_model_stats_df

   mean_diff  ci_lower  ci_upper                metric          method
0   2.000798  1.472238  2.529357        benefit_answer  + model labels
1   0.015168 -0.122318  0.152655          rigor_answer  + model labels
2   0.548827  0.320766  0.776888     importance_answer  + model labels
3   0.896187  0.611265  1.181110      full_text_answer  + model labels
4   1.189832  0.825996  1.553667  another_trial_answer  + model labels

In [45]:
# combined_detection_interpretation_overall_metrics.json was manually created
combined_interpretation_stats_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/combined_detection_interpretation_overall_metrics_all_new.json", orient="index")

combined_interpretation_stats_df["model_name"] = combined_interpretation_stats_df.index
combined_interpretation_stats_df["model_type"] = combined_interpretation_stats_df.index.map(lambda x: model_metadata[x]["model_type"])
combined_interpretation_stats_df["model_size_in_b"] = combined_interpretation_stats_df.index.map(lambda x: model_metadata[x]["model_size_in_b"])
# remove index
combined_interpretation_stats_df.reset_index(drop=True, inplace=True)

print(f"Number of models: {len(combined_interpretation_stats_df)}")

combined_interpretation_stats_df.sort_index(inplace=True) # alphabetical order
# combined_interpretation_stats_df

Number of models: 22

In [46]:
# calculate the average of all model metrics and calculate 95% CI
combined_interpretation_stats_df = calculate_model_stats(combined_interpretation_stats_df, method_name = "detect + interpret")
combined_interpretation_stats_df

   mean_diff  ci_lower  ci_upper                metric              method
0   1.095852  0.822521  1.369182        benefit_answer  detect + interpret
1  -0.241909 -0.491878  0.008060          rigor_answer  detect + interpret
2   0.377618 -0.065068  0.820304     importance_answer  detect + interpret
3   0.285100  0.013420  0.556779      full_text_answer  detect + interpret
4   0.773424  0.525767  1.021080  another_trial_answer  detect + interpret

In [47]:
all_results = pd.concat([human_expert_stats_df, model_stats_df, gold_labelled_model_stats_df, model_output_labelled_model_stats_df, combined_interpretation_stats_df], ignore_index=True)

all_results

    mean_diff  ci_lower  ci_upper                metric              method
0    0.710000  0.070000  1.350000        benefit_answer       human experts
1   -0.590000 -1.130000 -0.050000          rigor_answer       human experts
2   -0.380000 -0.950000  0.190000     importance_answer       human experts
3    0.770000  0.080000  1.470000      full_text_answer       human experts
4    0.640000 -0.030000  1.310000  another_trial_answer       human experts
5    1.991332  1.567488  2.415176        benefit_answer            baseline
6    0.134005  0.032919  0.235091          rigor_answer            baseline
7    0.782012  0.387193  1.176831     importance_answer            baseline
8    1.471335  1.026661  1.916010      full_text_answer            baseline
9    1.345742  1.051612  1.639871  another_trial_answer            baseline
10   1.046383  0.677622  1.415144        benefit_answer        + ref labels
11  -1.066753 -1.419150 -0.714357          rigor_answer        + ref labels
12  -0.447535 -0.731092 -0.163978     importance_answer        + ref labels
13  -0.192852 -0.670337  0.284633      full_text_answer        + ref labels
14   0.341208  0.019668  0.662749  another_trial_answer        + ref labels
15   2.000798  1.472238  2.529357        benefit_answer      + model labels
16   0.015168 -0.122318  0.152655          rigor_answer      + model labels
17   0.548827  0.320766  0.776888     importance_answer      + model labels
18   0.896187  0.611265  1.181110      full_text_answer      + model labels
19   1.189832  0.825996  1.553667  another_trial_answer      + model labels
20   1.095852  0.822521  1.369182        benefit_answer  detect + interpret
21  -0.241909 -0.491878  0.008060          rigor_answer  detect + interpret
22   0.377618 -0.065068  0.820304     importance_answer  detect + interpret
23   0.285100  0.013420  0.556779      full_text_answer  detect + interpret
24   0.773424  0.525767  1.021080  another_trial_answer  detect + interpret

In [48]:
# Create a mapping for custom facet titles
facet_title_mapping = {
    'benefit_answer': 'Treatment Benefit',
    'rigor_answer': 'Study Rigor',
    'importance_answer': 'Study Importance',
    'full_text_answer': 'Interest to Read Full-Text',
    'another_trial_answer': 'Interest to Run Another Trial'
}

# Define the desired order for the facets
facet_order = ['Treatment Benefit', 'Study Rigor', 'Study Importance', 'Interest to Read Full-Text', 'Interest to Run Another Trial']

color_mapping = {
    'human experts': '#0868ac',  
    'baseline': '#43a2ca',  
    '+ ref labels': '#7bccc4',  
    '+ model labels': '#bae4bc', 
    'detect + interpret': '#E3F4D4'  
}

method_order = ['human experts', 'baseline', '+ ref labels', '+ model labels', 'detect + interpret']

# Apply the mapping as a calculated field
chart_data = all_results.copy()
chart_data['metric'] = chart_data['metric'].map(facet_title_mapping)

# Configure global font sizes
chart_config = {
    "axis": {"labelFontSize": 20, "titleFontSize": 22},  # Axis labels and titles
    "header": {"labelFontSize": 20, "titleFontSize": 22},  # Facet headers
    "legend": {"labelFontSize": 18, "titleFontSize": 20},  # Legend labels and titles
    "text": {"fontSize": 20},  # Text mark size
}

# Bar chart
bars = alt.Chart(chart_data).mark_bar().encode(
    x=alt.X('method:N', title=None, axis=alt.Axis(labelAngle=-45), sort = method_order),
    y=alt.Y('mean_diff:Q', title='Mean Difference'),
    color=alt.Color('method:N', title='Method', legend=None, scale=alt.Scale(domain=list(color_mapping.keys()), range=list(color_mapping.values())))
).properties(
    width=300,  # Set the width to 300 pixels
    height=300  # Set the height to 300 pixels
)

# Error bars
error_bars = alt.Chart(chart_data).mark_errorbar().encode(
    alt.X("method:N", sort = method_order),
    alt.Y("ci_lower:Q").title("Mean Difference"),
    alt.Y2("ci_upper:Q"),
    strokeWidth=alt.value(2),
    color=alt.value('gray')
)

# Add value labels
text = bars.mark_text(
    align='center',
    baseline='bottom',
    fontWeight='bold',
    dy=alt.expr(expr=alt.expr.if_(alt.datum.mean_diff >= 0, -1, 22))  # Adjust the position of the text    
).encode(
    text=alt.Text('mean_diff:Q', format='.2f'),
    color=alt.value('black')  # Set text color to black
)

# Combine layers and facet
chart = alt.layer(bars, error_bars, text, data=chart_data).facet(
    column=alt.Column('metric:N', title=None, sort=facet_order),
).configure(**chart_config)  # Apply the global configuration

# save to html
chart.save("./plots/interpretation_by_measures_all_methods.html")

chart

alt.FacetChart(...)

In [49]:
interpretation_stats_df["method_category"] = "baseline"
gold_labelled_interpretation_stats_df["method_category"] = "gold_labelled"
model_output_labelled_interpretation_stats_df["method_category"] = "model_output_labelled"

all_interpretation_stats_df = pd.concat([interpretation_stats_df, gold_labelled_interpretation_stats_df, model_output_labelled_interpretation_stats_df], ignore_index=True)

all_interpretation_stats_df

,benefit_answer_mean_diff,rigor_answer_mean_diff,importance_answer_mean_diff,full_text_answer_mean_diff,another_trial_answer_mean_diff,overall_mean_diff_avg,model_name,model_type,model_size_in_b,method_category
0,3.377778,0.420000,1.100000,2.160000,1.573333,1.726222,olmo2_instruct-7B,generalist open,7.0,baseline
1,2.946667,0.766667,1.753333,3.013333,2.440000,2.184000,olmo2_instruct-13B,generalist open,13.0,baseline
2,1.766667,0.046667,1.620000,1.580000,1.253333,1.253333,mistral_instruct7B,generalist open,7.0,baseline
3,2.226667,0.240000,0.933333,1.120000,1.653333,1.234667,med42-8B,biomedical open,8.0,baseline
4,0.626667,0.026667,0.786667,0.547619,0.496667,0.496857,biomistral7B,biomedical open,7.0,baseline
...,...,...,...,...,...,...,...,...,...,...
61,1.753333,-0.006667,0.533333,1.313333,1.460000,1.010667,gpt4o-mini,generalist closed,NaN,model_output_labelled
62,0.720000,-0.400000,0.393333,0.613333,0.900000,0.445333,gemini_1.5_flash,generalist closed,NaN,model_output_labelled
63,1.353333,-0.720000,0.100000,0.860000,1.113333,0.541333,gemini_1.5_flash-8B,generalist closed,8.0,model_output_labelled
64,1.440000,-0.166667,0.100000,1.613333,1.260000,0.849333,claude_3.5-sonnet,generalist closed,NaN,model_output_labelled
65,1.193333,-0.193333,0.260000,0.860000,1.466667,0.717333,claude_3.5-haiku,generalist closed,NaN,model_output_labelled

In [50]:
from statsmodels.stats.multicomp import pairwise_tukeyhsd

# fit the model
model = smf.ols(formula="benefit_answer_mean_diff ~ method_category", 
                            data=all_interpretation_stats_df)
results = model.fit()

print(results.summary())


tukey_oneway = pairwise_tukeyhsd(endog = all_interpretation_stats_df["benefit_answer_mean_diff"], groups = all_interpretation_stats_df["method_category"])

# Display the results
tukey_oneway.summary()

                               OLS Regression Results
====================================================================================
Dep. Variable:     benefit_answer_mean_diff   R-squared:                       0.151
Model:                                  OLS   Adj. R-squared:                  0.123
Method:                       Least Squares   F-statistic:                     5.404
Date:                      Mon, 15 Sep 2025   Prob (F-statistic):            0.00691
Time:                              10:13:46   Log-Likelihood:                -93.679
No. Observations:                        64   AIC:                             193.4
Df Residuals:                            61   BIC:                             199.8
Df Model:                                 2
Covariance Type:                  nonrobust
============================================================================================================
                                               coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------------------------------------
Intercept                                    1.9913      0.228      8.719      0.000       1.535       2.448
method_category[T.gold_labelled]            -0.9449      0.331     -2.855      0.006      -1.607      -0.283
method_category[T.model_output_labelled]     0.0095      0.323      0.029      0.977      -0.636       0.655
==============================================================================
Omnibus:                        2.925   Durbin-Watson:                   2.159
Prob(Omnibus):                  0.232   Jarque-Bera (JB):                2.360
Skew:                           0.179   Prob(JB):                        0.307
Kurtosis:                       3.870   Cond. No.                         3.69
==============================================================================

Notes:
[1] Standard Errors assume that the covariance matrix of the errors is correctly specified.

In [51]:
# Create forest plot that shows the difference in scores between baseline and detect + interpret method for treatment benefit
custom_labels = {
    "alpacare-7B": "AlpaCare 7B",
    "biomedgpt7B": "BioMedGPT 7B",
    "biomistral7B": "BioMistral 7B",
    "claude_3.5-haiku": "Claude3.5 Haiku",
    "claude_3.5-sonnet": "Claude3.5 Sonnet", 
    "gemini_1.5_flash": "Gemini1.5 Flash",
    "gemini_1.5_flash-8B": "Gemini1.5 Flash 8B",
    "gpt4o": "GPT-4o",
    "gpt4o-mini": "GPT-4o Mini",
    "gpt35": "GPT-3.5",
    "llama2_chat-7B": "Llama2 Chat 7B",
    "llama2_chat-13B": "Llama2 Chat 13B",
    "llama2_chat-70B": "Llama2 Chat 70B",
    "llama3_instruct-8B": "Llama3 Instruct 8B",
    "llama3_instruct-70B": "Llama3 Instruct 70B",
    "med42-8B": "Med42 8B",
    "med42-70B": "Med42 70B",
    "mistral_instruct7B": "Mistral Instruct 7B",
    "olmo2_instruct-7B": "Olmo2 Instruct 7B",
    "olmo2_instruct-13B": "Olmo2 Instruct 13B",
    "openbiollm-8B": "OpenBioLLM 8B",
    "openbiollm-70B": "OpenBioLLM 70B"
}

baseline_stats_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/interpretation_overall_metrics_all_new.json", orient="index")
baseline_stats_df["model_name"] = baseline_stats_df.index
baseline_stats_df.drop(["overall_mean_diff_avg", "rigor_answer_mean_diff", "importance_answer_mean_diff", "full_text_answer_mean_diff", "another_trial_answer_mean_diff"], axis=1, inplace=True)
# remove index
baseline_stats_df.reset_index(drop=True, inplace=True)
# rename column name benefit_answer_mean_diff to baseline_benefit
baseline_stats_df.rename(columns={"benefit_answer_mean_diff": "baseline_benefit"}, inplace=True)

combined_interpretation_stats_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/combined_detection_interpretation_overall_metrics_all_new.json", orient="index")
combined_interpretation_stats_df["model_name"] = combined_interpretation_stats_df.index
combined_interpretation_stats_df.drop(["overall_avg", "rigor_answer_mean_diff", "importance_answer_mean_diff", "full_text_answer_mean_diff", "another_trial_answer_mean_diff"], axis=1, inplace=True)
# remove index
combined_interpretation_stats_df.reset_index(drop=True, inplace=True)
# rename column name benefit_answer_mean_diff to detect_interpret_benefit
combined_interpretation_stats_df.rename(columns={"benefit_answer_mean_diff": "detect_interpret_benefit"}, inplace=True)

# merge the dataframes by model_name
combined_methods_stats_df = pd.merge(baseline_stats_df, combined_interpretation_stats_df, on="model_name")
combined_methods_stats_df["model_name_custom"] = combined_methods_stats_df["model_name"].map(custom_labels)

combined_methods_stats_df

,baseline_benefit,model_name,detect_interpret_benefit,model_name_custom
0,3.377778,olmo2_instruct-7B,0.913333,Olmo2 Instruct 7B
1,2.946667,olmo2_instruct-13B,0.640000,Olmo2 Instruct 13B
2,1.766667,mistral_instruct7B,1.193333,Mistral Instruct 7B
3,2.226667,med42-8B,0.920000,Med42 8B
4,0.626667,biomistral7B,1.102564,BioMistral 7B
5,3.401575,openbiollm-8B,0.300000,OpenBioLLM 8B
6,1.663194,llama2_chat-7B,1.200000,Llama2 Chat 7B
7,2.402027,llama2_chat-13B,0.260000,Llama2 Chat 13B
8,1.686667,llama3_instruct-8B,0.626667,Llama3 Instruct 8B
9,1.672932,llama2_chat-70B,0.880000,Llama2 Chat 70B
10,2.640000,llama3_instruct-70B,2.280000,Llama3 Instruct 70B
11,3.180702,med42-70B,2.400000,Med42 70B
12,3.428667,openbiollm-70B,2.486667,OpenBioLLM 70B
13,0.257426,biomedgpt7B,1.170139,BioMedGPT 7B
14,-0.375000,alpacare-7B,NaN,AlpaCare 7B
15,2.646667,gpt35,1.856667,GPT-3.5
16,1.753333,gpt4o,0.653333,GPT-4o
17,2.306667,gpt4o-mini,1.133333,GPT-4o Mini
18,1.940000,gemini_1.5_flash,0.473333,Gemini1.5 Flash
19,1.593333,gemini_1.5_flash-8B,1.080000,Gemini1.5 Flash 8B
20,1.000000,claude_3.5-sonnet,1.020979,Claude3.5 Sonnet
21,1.666667,claude_3.5-haiku,0.422535,Claude3.5 Haiku

In [52]:
model_order = ['Claude3.5 Sonnet', 
    'GPT-4o Mini', 'Gemini1.5 Flash 8B', 'Llama3 Instruct 8B', 'Llama3 Instruct 70B', 'OpenBioLLM 70B', 'Med42 70B',
    'GPT-4o', 'Gemini1.5 Flash', 'Olmo2 Instruct 7B', 'AlpaCare 7B', 'Llama2 Chat 70B', 'Med42 8B', 'Claude3.5 Haiku', 'Llama2 Chat 13B',
    'GPT-3.5', 'BioMistral 7B', 'Olmo2 Instruct 13B', 'OpenBioLLM 8B', 'Mistral Instruct 7B', 'Llama2 Chat 7B', 'BioMedGPT 7B']

bar = alt.Chart(combined_methods_stats_df).mark_bar(cornerRadius=10, height=10).encode(
    x=alt.X('detect_interpret_benefit:Q').scale(domain=[-2, 6.5]).title('Mean Difference for Treatment Benefit'),
    x2='baseline_benefit:Q',
    y=alt.Y('model_name_custom:N', title="LLM Name", sort=model_order)  # Specify custom order
)

text_min = alt.Chart(combined_methods_stats_df).mark_text(align='right', dx=-5, fontSize=14, fontWeight='bold').encode(
    x='detect_interpret_benefit:Q',
    y=alt.Y('model_name_custom:N', sort=model_order),
    text=alt.Text('detect_interpret_benefit:Q', format='.2f'),
    color=alt.value('#FF8100')  # Set text color to orange
)

text_max = alt.Chart(combined_methods_stats_df).mark_text(align='left', dx=5, fontSize=14, fontWeight='bold').encode(
    x='baseline_benefit:Q',
    y=alt.Y('model_name_custom:N', sort=model_order),
    text=alt.Text('baseline_benefit:Q', format='.2f')
)

chart = (bar + text_min + text_max).properties(
    width=800,
    config={
        'axis': {
            'labelFontSize': 16,
            'titleFontSize': 18
        }
    })

# # Save to HTML
chart.save("./plots/baseline_detect_interpret_treatment_benefit_diff.html")

chart

alt.LayerChart(...)

## Relationship between spin / spin detection and spin interpretation

Linear Regression with statsmodels Python package

In [53]:
model_metadata = {
    "alpacare-7B": {"model_type": "biomedical open", "model_size_in_b": 7},
    "biomedgpt7B": {"model_type": "biomedical open", "model_size_in_b": 7},
    "biomistral7B": {"model_type": "biomedical open", "model_size_in_b": 7},
    "claude_3.5-haiku": {"model_type": "generalist closed", "model_size_in_b": None},
    "claude_3.5-sonnet": {"model_type": "generalist closed", "model_size_in_b": None},
    "gemini_1.5_flash": {"model_type": "generalist closed", "model_size_in_b": None},
    "gemini_1.5_flash-8B": {"model_type": "generalist closed", "model_size_in_b": 8},
    "gpt4o": {"model_type": "generalist closed", "model_size_in_b": None},
    "gpt4o-mini": {"model_type": "generalist closed", "model_size_in_b": None},
    "gpt35": {"model_type": "generalist closed", "model_size_in_b": 175},
    "llama2_chat-7B": {"model_type": "generalist open", "model_size_in_b": 7},
    "llama2_chat-13B": {"model_type": "generalist open", "model_size_in_b": 13},
    "llama2_chat-70B": {"model_type": "generalist open", "model_size_in_b": 70},
    "llama3_instruct-8B": {"model_type": "generalist open", "model_size_in_b": 8},
    "llama3_instruct-70B": {"model_type": "generalist open", "model_size_in_b": 70},
    "med42-8B": {"model_type": "biomedical open", "model_size_in_b": 8},
    "med42-70B": {"model_type": "biomedical open", "model_size_in_b": 70},
    "mistral_instruct7B": {"model_type": "generalist open", "model_size_in_b": 7},
    "olmo2_instruct-7B": {"model_type": "generalist open", "model_size_in_b": 7},
    "olmo2_instruct-13B": {"model_type": "generalist open", "model_size_in_b": 13},
    "openbiollm-8B": {"model_type": "biomedical open", "model_size_in_b": 8},
    "openbiollm-70B": {"model_type": "biomedical open", "model_size_in_b": 70}
}

In [54]:
# get all model names
model_names = model_metadata.keys()
# remove alpacare-13B
model_names = [x for x in model_names if x != "alpacare-13B"]

len(model_names)

22

In [55]:
measures = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer"]
gpt_models = ["gpt4o", "gpt4o-mini", "gpt35"]
huggingface_models = ["alpacare-7B", "biomedgpt7B", "biomistral7B", 
                      "llama2_chat-7B", "llama2_chat-13B", "llama2_chat-70B",
                      "llama3_instruct-8B", "llama3_instruct-70B",
                      "med42-8B", "med42-70B", "mistral_instruct7B", 
                      "olmo2_instruct-7B", "olmo2_instruct-13B",
                      "openbiollm-8B", "openbiollm-70B"]
no_probability_models = ["claude_3.5-haiku", "claude_3.5-sonnet", "gemini_1.5_flash-8B"]
# "gemini_1.5_flash",

def get_is_detection_correct(row):
    if row['abstract_type'] == "spin":
        return row['model_answer'] == "yes"
    else:
        return row['model_answer'] == "no"
    
def get_is_abstract_type_spin(row):
    return row['abstract_type'] == "spin"
    
def detection_probability_gpt(row):
    # find the first instance of "yes" or "no"
    token_probabilties = row['model_log_probabilities']
    for token_prob in token_probabilties:
        if token_prob['token'].lower() == "yes":
            return np.exp(token_prob['logprob'])
        elif token_prob['token'].lower() == "no":
            return np.exp(token_prob['logprob'])
    return None # this should not happen but just in case

def detection_probability_huggingface(row):
    # find the first instance of "yes" or "no"
    token_probabilties = row['model_log_probabilities']
    for token_prob in token_probabilties:
        if token_prob['token_string'].lower() == "yes":
            return token_prob['probability']
        elif token_prob['token_string'].lower() == "no":
            return token_prob['probability']
    return None # this should not happen but just in case


def prepare_data_for_regression(model_names):
    for model_name in tqdm(model_names):
        # print(f"Processing {model_name}...")
        final_data = []
        # detection_output_file_path = f"../data/biomedgpt7B_detection_outputs.json"
        # interpretation_output_file_path = f"../data/biomistral7B_detection_outputs.json"
        detection_output_file_path = f"../data/unspun_abstracts/analysis_gpt/{model_name}_detection_outputs.json"
        interpretation_output_file_path = f"../data/unspun_abstracts/analysis_gpt/{model_name}_interpretation_outputs.json"
        model_detection_data = pd.read_json(detection_output_file_path, orient="records")
        model_interpretation_data = pd.read_json(interpretation_output_file_path, orient="records")

        # merge model_detection_data and model_interpretation_data by PMID and abstract_type
        model_data = pd.merge(model_detection_data, model_interpretation_data, on=['PMID', 'abstract_type'])

        # loop through each row in model_data
        for _, row in model_data.iterrows():
            detection_model_prediction = 1 if row['model_answer'] == "yes" else 0
            is_detection_correct = 1 if get_is_detection_correct(row) else 0
            is_spin_in_abstract = 1 if get_is_abstract_type_spin(row) else 0

            if model_name in gpt_models:
                detection_probability = detection_probability_gpt(row)
            elif model_name in huggingface_models:
                detection_probability = detection_probability_huggingface(row)
            else:
                detection_probability = None
            
            for measure in measures:
                final_data.append({
                    "pmid": row['PMID'],
                    "measure": measure,
                    "is_spin_in_abstract": is_spin_in_abstract,
                    "is_detection_correct": is_detection_correct,
                    "detection_model_prediction": detection_model_prediction,
                    "detection_probability": detection_probability,
                    "interpretation_answer": float(row[measure]) if row[measure] != "" else None
                })
            # calculate the average of the differences
            answers = []
            for measure in measures:
                if row[measure] != "":
                    answers.append(float(row[measure]))
            if len(answers) > 0:
                avg_answer= round(np.mean(answers), 6)
            else:
                avg_answer = None
            # add the average difference to the data
            final_data.append({
                "pmid": row['PMID'],
                "measure": "overall",
                "is_spin_in_abstract": is_spin_in_abstract,
                "is_detection_correct": is_detection_correct,
                "detection_model_prediction": detection_model_prediction,
                "detection_probability": detection_probability,
                "interpretation_answer": avg_answer
            })

        # save the final data to a json file
        json_file_path = f"../data/unspun_abstracts/analysis_gpt/{model_name}_combined_data_all_new.csv"
        save_dataset_to_csv(final_data, json_file_path)

In [56]:
prepare_data_for_regression(model_names=model_names)

  0%|          | 0/22 [00:00<?, ?it/s]

100%|██████████| 22/22 [00:07<00:00,  3.13it/s]

#### Simplest Regression

Is spin in abstract and the measures answers

In [57]:
all_stats = {"benefit_answer":{},
             "rigor_answer": {},
             "importance_answer": {},
             "full_text_answer": {},
             "another_trial_answer": {}}

for model_name in model_names:
    output_string = ""
    csv_file_path = f"../data/unspun_abstracts/analysis_gpt/{model_name}_combined_data_all_new.csv"
    data = pd.read_csv(csv_file_path)

    measures = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer"]
    for measure in measures:
        # get the data for the current measure
        measure_data = data[data['measure'] == measure]
        nan_rows_number = measure_data['interpretation_answer'].isnull().sum()
        # remove rows with NaN values in interpretation_answer
        measure_data = measure_data.dropna(subset=['interpretation_answer'])

        # check if there are less than 2 rows
        if len(measure_data) < 2:
            continue
        
        # fit the model
        model = smf.ols(formula="interpretation_answer ~ is_spin_in_abstract", 
                                    data=measure_data)
        results = model.fit()

        stats = {}

        output_string += f"Model: {model_name} - {measure}\n"
        # print number of rows with NaN value(s)
        output_string += f"Number of rows with NaN value(s) in {model_name}: {nan_rows_number}\n"
        output_string += results.summary().as_text()
        output_string += "\n"

        stats["coef"] = results.params[1]
        stats["ci_lower"] = results.conf_int()[0][1]
        stats["ci_upper"] = results.conf_int()[1][1]
        stats["p_value"] = results.f_pvalue
        stats["r_squared"] = results.rsquared
        stats["adjusted_r_squared"] = results.rsquared_adj

        all_stats[measure][model_name] = stats

/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1871: RuntimeWarning: invalid value encountered in scalar divide
  return self.mse_model/self.mse_resid
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:955: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:50: RuntimeWarning: invalid value encountered in scalar divide
  dw = np.sum(diff_resids**2, axis=axis) / np.sum(resids**2, axis=axis)
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1871: RuntimeWarning: invalid value encountered in scalar divide
  return self.mse_model/self.mse_resid
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:955: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:50: RuntimeWarning: invalid value encountered in scalar divide
  dw = np.sum(diff_resids**2, axis=axis) / np.sum(resids**2, axis=axis)
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]
/tmp/ipykernel_4096095/4137041081.py:39: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_upper"] = results.conf_int()[1][1]
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/tmp/ipykernel_4096095/4137041081.py:37: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["coef"] = results.params[1]
/tmp/ipykernel_4096095/4137041081.py:38: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  stats["ci_lower"] = results.conf_int()[0][1]

In [58]:
all_stats

{'benefit_answer': {'alpacare-7B': {'coef': np.float64(1.4622641509433967),
   'ci_lower': np.float64(-0.1398537490406404),
   'ci_upper': np.float64(3.064382050927434),
   'p_value': np.float64(0.07313730638680997),
   'r_squared': np.float64(0.03448499438433983),
   'adjusted_r_squared': np.float64(0.023990266062430488)},
  'biomedgpt7B': {'coef': np.float64(0.018991596638654795),
   'ci_lower': np.float64(-0.7457285528395464),
   'ci_upper': np.float64(0.783711746116856),
   'p_value': np.float64(0.9610235826852371),
   'r_squared': np.float64(9.888926920664787e-06),
   'adjusted_r_squared': np.float64(-0.004122301614703616)},
  'biomistral7B': {'coef': np.float64(0.6118421052631561),
   'ci_lower': np.float64(0.36763613608203394),
   'ci_upper': np.float64(0.8560480744442782),
   'p_value': np.float64(1.3568617703010543e-06),
   'r_squared': np.float64(0.07449419911630184),
   'adjusted_r_squared': np.float64(0.07142961037165396)},
  'claude_3.5-haiku': {'coef': np.float64(1.6666666666666679),
   'ci_lower': np.float64(-3.2305221847839602),
   'ci_upper': np.float64(6.563855518117296),
   'p_value': np.float64(0.39820792722870463),
   'r_squared': np.float64(0.18248175182481752),
   'adjusted_r_squared': np.float64(-0.021897810218978186)},
  'claude_3.5-sonnet': {'coef': np.float64(1.0000000000000004),
   'ci_lower': np.float64(-3.4384543194183004),
   'ci_upper': np.float64(5.438454319418302),
   'p_value': np.float64(0.5655332664528661),
   'r_squared': np.float64(0.08910891089108897),
   'adjusted_r_squared': np.float64(-0.13861386138613874)},
  'gemini_1.5_flash': {'coef': np.float64(1.9539473684210513),
   'ci_lower': np.float64(1.5605538579768594),
   'ci_upper': np.float64(2.3473408788652432),
   'p_value': np.float64(8.758012555390615e-20),
   'r_squared': np.float64(0.24031548405552294),
   'adjusted_r_squared': np.float64(0.23779997241332274)},
  'gemini_1.5_flash-8B': {'coef': np.float64(1.6118421052631566),
   'ci_lower': np.float64(1.251451612859271),
   'ci_upper': np.float64(1.9722325976670423),
   'p_value': np.float64(1.0667106530127528e-16),
   'r_squared': np.float64(0.2041340329947252),
   'adjusted_r_squared': np.float64(0.20149871522318463)},
  'gpt4o': {'coef': np.float64(1.7697368421052624),
   'ci_lower': np.float64(1.4097778039135518),
   'ci_upper': np.float64(2.129695880296973),
   'p_value': np.float64(1.839589282678204e-19),
   'r_squared': np.float64(0.23661071927225874),
   'adjusted_r_squared': np.float64(0.23408294019700138)},
  'gpt4o-mini': {'coef': np.float64(2.31578947368421),
   'ci_lower': np.float64(1.9085745830823382),
   'ci_upper': np.float64(2.723004364286082),
   'p_value': np.float64(1.4949096203135396e-24),
   'r_squared': np.float64(0.29313346960405784),
   'adjusted_r_squared': np.float64(0.29079285195374016)},
  'gpt35': {'coef': np.float64(2.6776315789473673),
   'ci_lower': np.float64(2.2898993971459243),
   'ci_upper': np.float64(3.0653637607488102),
   'p_value': np.float64(3.774319134228154e-33),
   'r_squared': np.float64(0.37947022750024617),
   'adjusted_r_squared': np.float64(0.3774154931542205)},
  'llama2_chat-7B': {'coef': np.float64(1.7148648648648668),
   'ci_lower': np.float64(1.3381044812087892),
   'ci_upper': np.float64(2.0916252485209443),
   'p_value': np.float64(3.7915348270831595e-17),
   'r_squared': np.float64(0.21326555628190358),
   'adjusted_r_squared': np.float64(0.21060766964772093)},
  'llama2_chat-13B': {'coef': np.float64(2.442273730684326),
   'ci_lower': np.float64(2.0393065987385874),
   'ci_upper': np.float64(2.8452408626300647),
   'p_value': np.float64(4.3477234948200614e-27),
   'r_squared': np.float64(0.32238780203676376),
   'adjusted_r_squared': np.float64(0.3201215405051141)},
  'llama2_chat-70B': {'coef': np.float64(1.7167832167832155),
   'ci_lower': np.float64(1.4179750625036411),
   'ci_upper': np.float64(2.01559137106279),
   'p_value': np.float64(9.934823571080835e-25),
   'r_squared': np.float64(0.3105029359071949),
   'adjusted_r_squared': np.float64(0.3080751293434878)},
  'llama3_instruct-8B': {'coef': np.float64(1.690789473684211),
   'ci_lower': np.float64(1.4204384761781688),
   'ci_upper': np.float64(1.9611404711902534),
   'p_value': np.float64(1.738146516094993e-28),
   'r_squared': np.float64(0.3340143519618899),
   'adjusted_r_squared': np.float64(0.3318091014716975)},
  'llama3_instruct-70B': {'coef': np.float64(2.657894736842105),
   'ci_lower': np.float64(2.1354470912969084),
   'ci_upper': np.float64(3.1803423823873014),
   'p_value': np.float64(1.46357662432506e-20),
   'r_squared': np.float64(0.24917560272600703),
   'adjusted_r_squared': np.float64(0.24668942922509984)},
  'med42-8B': {'coef': np.float64(2.2368421052631575),
   'ci_lower': np.float64(1.9229620405152166),
   'ci_upper': np.float64(2.5507221700110985),
   'p_value': np.float64(9.404715130935396e-35),
   'r_squared': np.float64(0.3943831111232412),
   'adjusted_r_squared': np.float64(0.3923777571865632)},
  'med42-70B': {'coef': np.float64(3.6841441441441445),
   'ci_lower': np.float64(2.9426704104746313),
   'ci_upper': np.float64(4.425617877813657),
   'p_value': np.float64(1.9508669230032037e-18),
   'r_squared': np.float64(0.3494044159654215),
   'adjusted_r_squared': np.float64(0.34576980376411093)},
  'mistral_instruct7B': {'coef': np.float64(1.782894736842104),
   'ci_lower': np.float64(1.503728714240653),
   'ci_upper': np.float64(2.062060759443555),
   'p_value': np.float64(2.0100639890719094e-29),
   'r_squared': np.float64(0.34340208451204735),
   'adjusted_r_squared': np.float64(0.34122791922897466)},
  'olmo2_instruct-7B': {'coef': np.float64(3.5001958480219373),
   'ci_lower': np.float64(2.9615570382951653),
   'ci_upper': np.float64(4.038834657748709),
   'p_value': np.float64(6.840003506284285e-30),
   'r_squared': np.float64(0.3655111678287768),
   'adjusted_r_squared': np.float64(0.36327705222254003)},
  'olmo2_instruct-13B': {'coef': np.float64(2.999999999999998),
   'ci_lower': np.float64(2.4780540008983785),
   'ci_upper': np.float64(3.521945999101617),
   'p_value': np.float64(5.745529196795467e-25),
   'r_squared': np.float64(0.2975615340583858),
   'adjusted_r_squared': np.float64(0.2952355788731488)},
  'openbiollm-8B': {'coef': np.float64(3.3296568627450993),
   'ci_lower': np.float64(2.7546570620831896),
   'ci_upper': np.float64(3.904656663407009),
   'p_value': np.float64(5.939453999358526e-25),
   'r_squared': np.float64(0.31853050214248246),
   'adjusted_r_squared': np.float64(0.31607917301349864)},
  'openbiollm-70B': {'coef': np.float64(3.423026315789472),
   'ci_lower': np.float64(2.9711898326150927),
   'ci_upper': np.float64(3.8748627989638513),
   'p_value': np.float64(4.750469271607786e-38),
   'r_squared': np.float64(0.42393907251253427),
   'adjusted_r_squared': np.float64(0.4220315859976752)}},
 'rigor_answer': {'alpacare-7B': {'coef': np.float64(0.0646853146853139),
   'ci_lower': np.float64(-0.16139338784118318),
   'ci_upper': np.float64(0.290764017211811),
   'p_value': np.float64(0.5735649761852755),
   'r_squared': np.float64(0.001294675281442892),
   'adjusted_r_squared': np.float64(-0.002781672982714589)},
  'biomedgpt7B': {'coef': np.float64(-0.40000000000000036),
   'ci_lower': np.float64(-0.9629819831332482),
   'ci_upper': np.float64(0.16298198313324752),
   'p_value': np.float64(0.1611942696385648),
   'r_squared': np.float64(0.02500992457324347),
   'adjusted_r_squared': np.float64(0.012510051811362)},
  'biomistral7B': {'coef': np.float64(0.013157894736840106),
   'ci_lower': np.float64(-0.11098368917389885),
   'ci_upper': np.float64(0.13729947864757908),
   'p_value': np.float64(0.8349210386353851),
   'r_squared': np.float64(0.0001440299582313731),
   'adjusted_r_squared': np.float64(-0.003166751399522827)},
  'claude_3.5-haiku': {'coef': np.float64(-8.881784197001252e-16),
   'ci_lower': np.float64(-2.631888628348343e-15),
   'ci_upper': np.float64(8.555317889480926e-16),
   'p_value': np.float64(1.0),
   'r_squared': np.float64(-inf),
   'adjusted_r_squared': np.float64(-inf)},
  'claude_3.5-sonnet': {'coef': np.float64(-8.881784197001252e-16),
   'ci_lower': np.float64(-2.631888628348343e-15),
   'ci_upper': np.float64(8.555317889480926e-16),
   'p_value': np.float64(1.0),
   'r_squared': np.float64(-inf),
   'adjusted_r_squared': np.float64(-inf)},
  'gemini_1.5_flash': {'coef': np.float64(0.06578947368420844),
   'ci_lower': np.float64(-0.0973051462992834),
   'ci_upper': np.float64(0.2288840936677003),
   'p_value': np.float64(0.42793755800352684),
   'r_squared': np.float64(0.002082118764054397),
   'adjusted_r_squared': np.float64(-0.0012222450810976948)},
  'gemini_1.5_flash-8B': {'coef': np.float64(-0.09210526315789658),
   'ci_lower': np.float64(-0.23343969322777214),
   'ci_upper': np.float64(0.04922916691197898),
   'p_value': np.float64(0.20068064870427424),
   'r_squared': np.float64(0.005416160053056229),
   'adjusted_r_squared': np.float64(0.002122836079722079)},
  'gpt4o': {'coef': np.float64(0.15789473684210303),
   'ci_lower': np.float64(0.060464484849140424),
   'ci_upper': np.float64(0.25532498883506566),
   'p_value': np.float64(0.0015771321094697611),
   'r_squared': np.float64(0.032579185520361986),
   'adjusted_r_squared': np.float64(0.029375805339965977)},
  'gpt4o-mini': {'coef': np.float64(0.6578947368421039),
   'ci_lower': np.float64(0.45371567287769077),
   'ci_upper': np.float64(0.862073800806517),
   'p_value': np.float64(8.324341658647666e-10),
   'r_squared': np.float64(0.11748672400018811),
   'adjusted_r_squared': np.float64(0.11456449460946039)},
  'gpt35': {'coef': np.float64(0.35526315789473517),
   'ci_lower': np.float64(0.19521191014919306),
   'ci_upper': np.float64(0.5153144056402773),
   'p_value': np.float64(1.7254854033129397e-05),
   'r_squared': np.float64(0.05942288881643276),
   'adjusted_r_squared': np.float64(0.05630839507079188)},
  'llama2_chat-7B': {'coef': np.float64(0.15789473684210362),
   'ci_lower': np.float64(-0.04687061299641668),
   'ci_upper': np.float64(0.3626600866806239),
   'p_value': np.float64(0.13020902038784463),
   'r_squared': np.float64(0.0075666018601231455),
   'adjusted_r_squared': np.float64(0.004280398555024267)},
  'llama2_chat-13B': {'coef': np.float64(0.32236842105262975),
   'ci_lower': np.float64(0.11508969253847925),
   'ci_upper': np.float64(0.5296471495667803),
   'p_value': np.float64(0.002408267040107984),
   'r_squared': np.float64(0.030082064774791806),
   'adjusted_r_squared': np.float64(0.026870415982655493)},
  'llama2_chat-70B': {'coef': np.float64(0.1381578947368398),
   'ci_lower': np.float64(0.025082693623623434),
   'ci_upper': np.float64(0.25123309585005615),
   'p_value': np.float64(0.016802578313198598),
   'r_squared': np.float64(0.018782742024788246),
   'adjusted_r_squared': np.float64(0.015533678256658523)},
  'llama3_instruct-8B': {'coef': np.float64(0.06578947368420841),
   'ci_lower': np.float64(-0.010737118325446035),
   'ci_upper': np.float64(0.14231606569386285),
   'p_value': np.float64(0.09172524197965132),
   'r_squared': np.float64(0.009387908374013931),
   'adjusted_r_squared': np.float64(0.006107735885186205)},
  'llama3_instruct-70B': {'coef': np.float64(0.03947368421052432),
   'ci_lower': np.float64(-0.046247660347513174),
   'ci_upper': np.float64(0.1251950287685618),
   'p_value': np.float64(0.3655671315330733),
   'r_squared': np.float64(0.002711660138596028),
   'adjusted_r_squared': np.float64(-0.000590619132468051)},
  'med42-8B': {'coef': np.float64(0.23684210526315574),
   'ci_lower': np.float64(0.13254481683973174),
   'ci_upper': np.float64(0.34113939368657975),
   'p_value': np.float64(1.1143196932687054e-05),
   'r_squared': np.float64(0.06202143950995398),
   'adjusted_r_squared': np.float64(0.05891555023680817)},
  'med42-70B': {'coef': np.float64(-1.9012569296705806e-15),
   'ci_lower': np.float64(-3.722742388156328e-15),
   'ci_upper': np.float64(-7.977147118483343e-17),
   'p_value': np.float64(1.0),
   'r_squared': np.float64(-inf),
   'adjusted_r_squared': np.float64(-inf)},
  'mistral_instruct7B': {'coef': np.float64(0.04605263157894539),
   'ci_lower': np.float64(-0.024362817917178287),
   'ci_upper': np.float64(0.11646808107506906),
   'p_value': np.float64(0.19907985911417433),
   'r_squared': np.float64(0.005454747857063236),
   'adjusted_r_squared': np.float64(0.00216155165791454)},
  'olmo2_instruct-7B': {'coef': np.float64(0.4276315789473665),
   'ci_lower': np.float64(0.3024083343774656),
   'ci_upper': np.float64(0.5528548235172673),
   'p_value': np.float64(9.045972658482153e-11),
   'r_squared': np.float64(0.13008405431201675),
   'adjusted_r_squared': np.float64(0.1272035379355666)},
  'olmo2_instruct-13B': {'coef': np.float64(0.7828947368421036),
   'ci_lower': np.float64(0.5359406803868494),
   'ci_upper': np.float64(1.029848793297358),
   'p_value': np.float64(1.4898280076746202e-09),
   'r_squared': np.float64(0.1141583432086225),
   'adjusted_r_squared': np.float64(0.1112250926894458)},
  'openbiollm-8B': {'coef': np.float64(0.17027292844848976),
   'ci_lower': np.float64(-0.32565161216579885),
   'ci_upper': np.float64(0.6661974690627783),
   'p_value': np.float64(0.49894866975425434),
   'r_squared': np.float64(0.002557898454392027),
   'adjusted_r_squared': np.float64(-0.003014403788879516)},
  'openbiollm-70B': {'coef': np.float64(-0.00328947368421241),
   'ci_lower': np.float64(-0.009762665221599657),
   'ci_upper': np.float64(0.003183717853174837),
   'p_value': np.float64(0.3181110717939539),
   'r_squared': np.float64(0.0033003300330031182),
   'adjusted_r_squared': np.float64(0.0)}},
 'importance_answer': {'alpacare-7B': {'coef': np.float64(-2.020535714285714),
   'ci_lower': np.float64(-3.548797050709503),
   'ci_upper': np.float64(-0.49227437786192496),
   'p_value': np.float64(0.010356767091409673),
   'r_squared': np.float64(0.09687030891548176),
   'adjusted_r_squared': np.float64(0.08297600597571997)},
  'biomedgpt7B': {'coef': np.float64(0.0),
   'ci_lower': np.float64(0.0),
   'ci_upper': np.float64(0.0),
   'p_value': np.float64(nan),
   'r_squared': np.float64(nan),
   'adjusted_r_squared': np.float64(nan)},
  'biomistral7B': {'coef': np.float64(0.7828947368421035),
   'ci_lower': np.float64(0.5316451176958297),
   'ci_upper': np.float64(1.0341443559883774),
   'p_value': np.float64(2.714721910979701e-09),
   'r_squared': np.float64(0.1107167150105941),
   'adjusted_r_squared': np.float64(0.1077720683715564)},
  'claude_3.5-haiku': {'coef': np.float64(0.33333333333333337),
   'ci_lower': np.float64(-0.9754954409850404),
   'ci_upper': np.float64(1.642162107651707),
   'p_value': np.float64(0.5185185185185183),
   'r_squared': np.float64(0.11111111111111116),
   'adjusted_r_squared': np.float64(-0.11111111111111116)},
  'claude_3.5-sonnet': {'coef': np.float64(-0.33333333333333304),
   'ci_lower': np.float64(-1.6421621076517068),
   'ci_upper': np.float64(0.9754954409850407),
   'p_value': np.float64(0.5185185185185183),
   'r_squared': np.float64(0.11111111111111116),
   'adjusted_r_squared': np.float64(-0.11111111111111116)},
  'gemini_1.5_flash': {'coef': np.float64(1.1184210526315783),
   'ci_lower': np.float64(0.788637723945711),
   'ci_upper': np.float64(1.4482043813174457),
   'p_value': np.float64(1.1923994064039383e-10),
   'r_squared': np.float64(0.1285244151916748),
   'adjusted_r_squared': np.float64(0.12563873444727647)},
  'gemini_1.5_flash-8B': {'coef': np.float64(0.8289473684210515),
   'ci_lower': np.float64(0.5911596334740359),
   'ci_upper': np.float64(1.0667351033680672),
   'p_value': np.float64(3.8990328217896086e-11),
   'r_squared': np.float64(0.13482115560990504),
   'adjusted_r_squared': np.float64(0.13195632499934185)},
  'gpt4o': {'coef': np.float64(0.526315789473683),
   'ci_lower': np.float64(0.33246043429857863),
   'ci_upper': np.float64(0.7201711446487873),
   'p_value': np.float64(1.8062819628466376e-07),
   'r_squared': np.float64(0.08635578583765136),
   'adjusted_r_squared': np.float64(0.08333047387022641)},
  'gpt4o-mini': {'coef': np.float64(1.5065789473684208),
   'ci_lower': np.float64(1.2154315952103028),
   'ci_upper': np.float64(1.7977262995265388),
   'p_value': np.float64(3.9558645972917295e-21),
   'r_squared': np.float64(0.2555915681735105),
   'adjusted_r_squared': np.float64(0.25312663959130366)},
  'gpt35': {'coef': np.float64(0.9999999999999991),
   'ci_lower': np.float64(0.7452384079848757),
   'ci_upper': np.float64(1.2547615920151225),
   'p_value': np.float64(1.6702206711080827e-13),
   'r_squared': np.float64(0.16497200959670977),
   'adjusted_r_squared': np.float64(0.16220701625100353)},
  'llama2_chat-7B': {'coef': np.float64(0.9802631578947353),
   'ci_lower': np.float64(0.7991516398950358),
   'ci_upper': np.float64(1.1613746758944348),
   'p_value': np.float64(1.0606127960111435e-22),
   'r_squared': np.float64(0.2730649545527226),
   'adjusted_r_squared': np.float64(0.2706578848658112)},
  'llama2_chat-13B': {'coef': np.float64(1.2039473684210522),
   'ci_lower': np.float64(0.953609488146032),
   'ci_upper': np.float64(1.4542852486960725),
   'p_value': np.float64(8.802732892646398e-19),
   'r_squared': np.float64(0.22873906302294278),
   'adjusted_r_squared': np.float64(0.22618521886076715)},
  'llama2_chat-70B': {'coef': np.float64(0.5921052631578934),
   'ci_lower': np.float64(0.4558165590692963),
   'ci_upper': np.float64(0.7283939672464904),
   'p_value': np.float64(6.272831174841582e-16),
   'r_squared': np.float64(0.19486143187066973),
   'adjusted_r_squared': np.float64(0.19219541012189723)},
  'llama3_instruct-8B': {'coef': np.float64(0.677631578947367),
   'ci_lower': np.float64(0.5100953892513964),
   'ci_upper': np.float64(0.8451677686433376),
   'p_value': np.float64(3.5258885667789144e-14),
   'r_squared': np.float64(0.17339783926907792),
   'adjusted_r_squared': np.float64(0.17066074602162462)},
  'llama3_instruct-70B': {'coef': np.float64(0.7763157894736833),
   'ci_lower': np.float64(0.5612343202988823),
   'ci_upper': np.float64(0.9913972586484843),
   'p_value': np.float64(8.810222877176451e-12),
   'r_squared': np.float64(0.1431391093383778),
   'adjusted_r_squared': np.float64(0.14030182162095528)},
  'med42-8B': {'coef': np.float64(0.934210526315788),
   'ci_lower': np.float64(0.747744984539974),
   'ci_upper': np.float64(1.1206760680916021),
   'p_value': np.float64(4.6228379770476624e-20),
   'r_squared': np.float64(0.24349128145679388),
   'adjusted_r_squared': np.float64(0.24098628570002834)},
  'med42-70B': {'coef': np.float64(0.5921052631578931),
   'ci_lower': np.float64(0.38300577481880677),
   'ci_upper': np.float64(0.8012047514969796),
   'p_value': np.float64(5.569061869649452e-08),
   'r_squared': np.float64(0.09323204419889497),
   'adjusted_r_squared': np.float64(0.0902295012988914)},
  'mistral_instruct7B': {'coef': np.float64(1.6184210526315788),
   'ci_lower': np.float64(1.355870598903102),
   'ci_upper': np.float64(1.8809715063600556),
   'p_value': np.float64(7.445355969817653e-28),
   'r_squared': np.float64(0.32760935469900376),
   'adjusted_r_squared': np.float64(0.32538289560860323)},
  'olmo2_instruct-7B': {'coef': np.float64(1.0986842105263142),
   'ci_lower': np.float64(0.8922425633177719),
   'ci_upper': np.float64(1.3051258577348563),
   'p_value': np.float64(4.237912920282111e-22),
   'r_squared': np.float64(0.26642402009954236),
   'adjusted_r_squared': np.float64(0.2639949605634482)},
  'olmo2_instruct-13B': {'coef': np.float64(1.7960526315789462),
   'ci_lower': np.float64(1.4527353576981517),
   'ci_upper': np.float64(2.139369905459741),
   'p_value': np.float64(1.67728390428709e-21),
   'r_squared': np.float64(0.25977072390320055),
   'adjusted_r_squared': np.float64(0.2573196335849993)},
  'openbiollm-8B': {'coef': np.float64(2.3475921442023133),
   'ci_lower': np.float64(1.2115319479851527),
   'ci_upper': np.float64(3.483652340419474),

In [12]:
import json
with open(f"../data/unspun_abstracts/analysis_gpt/simple_regression_summary_all_new.json", "w") as f:
    json.dump(all_stats, f, indent=4)

In [13]:
measures = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer"]
for measure in measures:
    with open(f"../data/unspun_abstracts/analysis_gpt/{measure}_simple_regression_summary_all_new.json", "w") as f:
        json.dump(all_stats[measure], f, indent=4)

In [14]:
all_stats = {"benefit_answer":{},
             "rigor_answer": {},
             "importance_answer": {},
             "full_text_answer": {},
             "another_trial_answer": {}}

for model_name in model_names:
    output_string = ""
    csv_file_path = f"../data/unspun_abstracts/analysis_gpt/{model_name}_combined_data_all_new.csv"
    data = pd.read_csv(csv_file_path)

    measures = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer", "overall"]
    for measure in measures:
        # get the data for the current measure
        measure_data = data[data['measure'] == measure]
        nan_rows_number = measure_data['interpretation_answer'].isnull().sum()
        # remove rows with NaN values in interpretation_answer
        measure_data = measure_data.dropna(subset=['interpretation_answer'])

        # check if there are less than 2 rows
        if len(measure_data) < 2:
            continue
        
        # fit the model
        model = smf.ols(formula="interpretation_answer ~ is_spin_in_abstract", 
                                    data=measure_data)
        results = model.fit()

        output_string += f"Model: {model_name} - {measure}\n"
        # print number of rows with NaN value(s)
        output_string += f"Number of rows with NaN value(s) in {model_name}: {nan_rows_number}\n"
        output_string += results.summary().as_text()
        output_string += "\n"

    # save the model summary
    with open(f"../data/unspun_abstracts/analysis_gpt/{model_name}_simple_regression_summary_all_new.txt", "w") as f:
        f.write(output_string)

/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1871: RuntimeWarning: invalid value encountered in scalar divide
  return self.mse_model/self.mse_resid
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:955: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:50: RuntimeWarning: invalid value encountered in scalar divide
  dw = np.sum(diff_resids**2, axis=axis) / np.sum(resids**2, axis=axis)
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: invalid value encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1871: RuntimeWarning: invalid value encountered in scalar divide
  return self.mse_model/self.mse_resid
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:955: RuntimeWarning: divide by zero encountered in log
  llf = -nobs2*np.log(2*np.pi) - nobs2*np.log(ssr / nobs) - nobs2
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:50: RuntimeWarning: invalid value encountered in scalar divide
  dw = np.sum(diff_resids**2, axis=axis) / np.sum(resids**2, axis=axis)
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/stats/stattools.py:74: ValueWarning: omni_normtest is not valid with less than 8 observations; 6 samples were given.
  warn("omni_normtest is not valid with less than 8 observations; %i "
/home/zhang.yuchen/.conda/envs/jup/lib/python3.12/site-packages/statsmodels/regression/linear_model.py:1782: RuntimeWarning: divide by zero encountered in scalar divide
  return 1 - self.ssr/self.centered_tss

##### Forest Plot for "Benefit" Linear Regression Results

In [22]:
import altair as alt
import pandas as pd

custom_labels = {
    "alpacare-7B": "AlpaCare 7B",
    "biomedgpt7B": "BioMedGPT 7B",
    "biomistral7B": "BioMistral 7B",
    "claude_3.5-haiku": "Claude3.5 Haiku",
    "claude_3.5-sonnet": "Claude3.5 Sonnet", 
    "gemini_1.5_flash": "Gemini1.5 Flash",
    "gemini_1.5_flash-8B": "Gemini1.5 Flash 8B",
    "gpt4o": "GPT-4o",
    "gpt4o-mini": "GPT-4o Mini",
    "gpt35": "GPT-3.5",
    "llama2_chat-7B": "Llama2 Chat 7B",
    "llama2_chat-13B": "Llama2 Chat 13B",
    "llama2_chat-70B": "Llama2 Chat 70B",
    "llama3_instruct-8B": "Llama3 Instruct 8B",
    "llama3_instruct-70B": "Llama3 Instruct 70B",
    "med42-8B": "Med42 8B",
    "med42-70B": "Med42 70B",
    "mistral_instruct7B": "Mistral Instruct 7B",
    "olmo2_instruct-7B": "Olmo2 Instruct 7B",
    "olmo2_instruct-13B": "Olmo2 Instruct 13B",
    "openbiollm-8B": "OpenBioLLM 8B",
    "openbiollm-70B": "OpenBioLLM 70B"
}

# Load the JSON data into a DataFrame
# this json file was manually created
regression_results_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/benefit_answer_simple_regression_summary_all_new.json", orient="index")

# Ensure index is reset and available as a column
regression_results_df.reset_index(inplace=True)
regression_results_df = regression_results_df.rename(columns={'index': 'model_name'})

regression_results_df["model_name_custom"] = regression_results_df["model_name"].map(custom_labels)

# Create the Altair chart
points = alt.Chart(regression_results_df).mark_point(
    filled=True,
    color='red',
    size=50  # Increase point size
).encode(
    x=alt.X('coef:Q').title('Coefficient'),
    y=alt.Y('model_name_custom:N').title('LLM Name').sort(
        field='coef',  # Sort by coefficient values
        order='descending'
    )
).properties(
    width=600,
    height=300
)

# Add error bars
error_bars = points.mark_rule(
    strokeWidth=2  # Increase width of error bars
).encode(
    x='ci_lower:Q',
    x2='ci_upper:Q',
    size=alt.value(2)  # Set the width of error bars
)

# Add vertical line at x = 0.71
vertical_line = alt.Chart(pd.DataFrame({'x': [0.71]})).mark_rule(
    color='blue',
    strokeDash=[4, 4],  # Make it dashed
    strokeWidth=2
).encode(
    x='x:Q',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Add label for vertical line
label = alt.Chart(pd.DataFrame({'x': [0.71], 'y': [regression_results_df['model_name_custom'].iloc[0]]})).mark_text(
    text='Human Experts',
    align='center',
    dx=5,  # Adjust text position
    dy=-10,
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    y=alt.value(0),  # Adjust position if necessary
    color=alt.value('#0868ac')  # Specify the color directly
)

# Define custom x-axis labels
custom_labels_df = pd.DataFrame({
    'x': [-2.5, 4.2],
    'text': ['Less susceptible to spin', 'More susceptible to spin']
})

# Define custom x-axis labels
left_arrow_df = pd.DataFrame({
    'x': [-4],
    'text': ['←']
})

# Define custom x-axis labels
right_arrow_df = pd.DataFrame({
    'x': [6.5],
    'text': ['→']
})

# Create a text layer for custom x-axis labels
custom_x_labels = alt.Chart(custom_labels_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=24, # adjust horizontal positioning
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_left_arrow = alt.Chart(left_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=10, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_right_arrow = alt.Chart(right_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=0, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Combine all layers, including the new x-axis labels
chart = alt.layer(error_bars, points, vertical_line, label, custom_x_labels, custom_x_left_arrow, custom_x_right_arrow).configure_axis(
    labelFontSize=16,
    titleFontSize=18
).configure_title(
    fontSize=20
)

# # Save to HTML
chart.save("./plots/simple_regression_benefit_data.html")

chart

alt.LayerChart(...)

In [ ]:
# rest of the questions

regression_results_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/another_trial_answer_simple_regression_summary_all_new.json", orient="index")

# Ensure index is reset and available as a column
regression_results_df.reset_index(inplace=True)
regression_results_df = regression_results_df.rename(columns={'index': 'model_name'})

regression_results_df["model_name_custom"] = regression_results_df["model_name"].map(custom_labels)

# Create the Altair chart
points = alt.Chart(regression_results_df).mark_point(
    filled=True,
    color='red',
    size=50  # Increase point size
).encode(
    x=alt.X('coef:Q').title('Coefficient'),
    y=alt.Y('model_name_custom:N').title('LLM Name').sort(
        field='coef',  # Sort by coefficient values
        order='descending'
    )
).properties(
    width=600,
    height=300
)

# Add error bars
error_bars = points.mark_rule(
    strokeWidth=2  # Increase width of error bars
).encode(
    x='ci_lower:Q',
    x2='ci_upper:Q',
    size=alt.value(2)  # Set the width of error bars
)

# Add vertical line
vertical_line = alt.Chart(pd.DataFrame({'x': [0.640000]})).mark_rule(
    color='blue',
    strokeDash=[4, 4],  # Make it dashed
    strokeWidth=2
).encode(
    x='x:Q',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Add label for vertical line
label = alt.Chart(pd.DataFrame({'x': [0.640000], 'y': [regression_results_df['model_name_custom'].iloc[0]]})).mark_text(
    text='Human Experts',
    align='center',
    dx=5,  # Adjust text position
    dy=-10,
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    y=alt.value(0),  # Adjust position if necessary
    color=alt.value('#0868ac')  # Specify the color directly
)

# Define custom x-axis labels
custom_labels_df = pd.DataFrame({
    'x': [-3.5, 4.7],
    'text': ['Less susceptible to spin', 'More susceptible to spin']
})

# Define custom x-axis labels
left_arrow_df = pd.DataFrame({
    'x': [-5.5],
    'text': ['←']
})

# Define custom x-axis labels
right_arrow_df = pd.DataFrame({
    'x': [7.5],
    'text': ['→']
})

# Create a text layer for custom x-axis labels
custom_x_labels = alt.Chart(custom_labels_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=24, # adjust horizontal positioning
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_left_arrow = alt.Chart(left_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=10, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_right_arrow = alt.Chart(right_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=0, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Combine all layers, including the new x-axis labels
chart = alt.layer(error_bars, points, vertical_line, label, custom_x_labels, custom_x_left_arrow, custom_x_right_arrow).configure_axis(
    labelFontSize=16,
    titleFontSize=18
).configure_title(
    fontSize=20
)

# Save to HTML
chart.save("./plots/simple_regression_another_trial_data.html")

chart

alt.LayerChart(...)

In [ ]:
custom_labels = {
    "alpacare-7B": "AlpaCare 7B",
    "biomedgpt7B": "BioMedGPT 7B",
    "biomistral7B": "BioMistral 7B",
    "claude_3.5-haiku": "Claude3.5 Haiku",
    "claude_3.5-sonnet": "Claude3.5 Sonnet", 
    "gemini_1.5_flash": "Gemini1.5 Flash",
    "gemini_1.5_flash-8B": "Gemini1.5 Flash 8B",
    "gpt4o": "GPT-4o",
    "gpt4o-mini": "GPT-4o Mini",
    "gpt35": "GPT-3.5",
    "llama2_chat-7B": "Llama2 Chat 7B",
    "llama2_chat-13B": "Llama2 Chat 13B",
    "llama2_chat-70B": "Llama2 Chat 70B",
    "llama3_instruct-8B": "Llama3 Instruct 8B",
    "llama3_instruct-70B": "Llama3 Instruct 70B",
    "med42-8B": "Med42 8B",
    "med42-70B": "Med42 70B",
    "mistral_instruct7B": "Mistral Instruct 7B",
    "olmo2_instruct-7B": "Olmo2 Instruct 7B",
    "olmo2_instruct-13B": "Olmo2 Instruct 13B",
    "openbiollm-8B": "OpenBioLLM 8B",
    "openbiollm-70B": "OpenBioLLM 70B"
}

In [ ]:
# rest of the questions

regression_results_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/rigor_answer_simple_regression_summary_all_new.json", orient="index")

# Ensure index is reset and available as a column
regression_results_df.reset_index(inplace=True)
regression_results_df = regression_results_df.rename(columns={'index': 'model_name'})

regression_results_df["model_name_custom"] = regression_results_df["model_name"].map(custom_labels)

# Create the Altair chart
points = alt.Chart(regression_results_df).mark_point(
    filled=True,
    color='red',
    size=50  # Increase point size
).encode(
    x=alt.X('coef:Q').title('Coefficient'),
    y=alt.Y('model_name_custom:N').title('LLM Name').sort(
        field='coef',  # Sort by coefficient values
        order='descending'
    )
).properties(
    width=600,
    height=300
)

# Add error bars
error_bars = points.mark_rule(
    strokeWidth=2  # Increase width of error bars
).encode(
    x='ci_lower:Q',
    x2='ci_upper:Q',
    size=alt.value(2)  # Set the width of error bars
)

# Add vertical line 
vertical_line = alt.Chart(pd.DataFrame({'x': [-0.590000]})).mark_rule(
    color='blue',
    strokeDash=[4, 4],  # Make it dashed
    strokeWidth=2
).encode(
    x='x:Q',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Add label for vertical line
label = alt.Chart(pd.DataFrame({'x': [0.640000], 'y': [regression_results_df['model_name_custom'].iloc[0]]})).mark_text(
    text='Human Experts',
    align='center',
    dx=5,  # Adjust text position
    dy=-10,
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    y=alt.value(0),  # Adjust position if necessary
    color=alt.value('#0868ac')  # Specify the color directly
)

# Define custom x-axis labels
custom_labels_df = pd.DataFrame({
    'x': [-0.66, 0.65],
    'text': ['Less susceptible to spin', 'More susceptible to spin']
})

# Define custom x-axis labels
left_arrow_df = pd.DataFrame({
    'x': [-1],
    'text': ['←']
})

# Define custom x-axis labels
right_arrow_df = pd.DataFrame({
    'x': [1.1],
    'text': ['→']
})

# Create a text layer for custom x-axis labels
custom_x_labels = alt.Chart(custom_labels_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=24, # adjust horizontal positioning
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_left_arrow = alt.Chart(left_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=10, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_right_arrow = alt.Chart(right_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=0, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Combine all layers, including the new x-axis labels
chart = alt.layer(error_bars, points, vertical_line, label, custom_x_labels, custom_x_left_arrow, custom_x_right_arrow).configure_axis(
    labelFontSize=16,
    titleFontSize=18
).configure_title(
    fontSize=20
)

# Save to HTML
chart.save("./plots/simple_regression_rigor_data.html")

chart

alt.LayerChart(...)

In [ ]:
# rest of the questions

regression_results_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/full_text_answer_simple_regression_summary_all_new.json", orient="index")

# Ensure index is reset and available as a column
regression_results_df.reset_index(inplace=True)
regression_results_df = regression_results_df.rename(columns={'index': 'model_name'})

regression_results_df["model_name_custom"] = regression_results_df["model_name"].map(custom_labels)

# Create the Altair chart
points = alt.Chart(regression_results_df).mark_point(
    filled=True,
    color='red',
    size=50  # Increase point size
).encode(
    x=alt.X('coef:Q').title('Coefficient'),
    y=alt.Y('model_name_custom:N').title('LLM Name').sort(
        field='coef',  # Sort by coefficient values
        order='descending'
    )
).properties(
    width=600,
    height=300
)

# Add error bars
error_bars = points.mark_rule(
    strokeWidth=2  # Increase width of error bars
).encode(
    x='ci_lower:Q',
    x2='ci_upper:Q',
    size=alt.value(2)  # Set the width of error bars
)

# Add vertical line
vertical_line = alt.Chart(pd.DataFrame({'x': [0.640000]})).mark_rule(
    color='blue',
    strokeDash=[4, 4],  # Make it dashed
    strokeWidth=2
).encode(
    x='x:Q',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Add label for vertical line
label = alt.Chart(pd.DataFrame({'x': [0.640000], 'y': [regression_results_df['model_name_custom'].iloc[0]]})).mark_text(
    text='Human Experts',
    align='center',
    dx=5,  # Adjust text position
    dy=-10,
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    y=alt.value(0),  # Adjust position if necessary
    color=alt.value('#0868ac')  # Specify the color directly
)

# Define custom x-axis labels
custom_labels_df = pd.DataFrame({
    'x': [-0.8, 4.2],
    'text': ['Less susceptible to spin', 'More susceptible to spin']
})

# Define custom x-axis labels
left_arrow_df = pd.DataFrame({
    'x': [-2],
    'text': ['←']
})

# Define custom x-axis labels
right_arrow_df = pd.DataFrame({
    'x': [5.8],
    'text': ['→']
})

# Create a text layer for custom x-axis labels
custom_x_labels = alt.Chart(custom_labels_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=24, # adjust horizontal positioning
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_left_arrow = alt.Chart(left_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=10, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_right_arrow = alt.Chart(right_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=0, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Combine all layers, including the new x-axis labels
chart = alt.layer(error_bars, points, vertical_line, label, custom_x_labels, custom_x_left_arrow, custom_x_right_arrow).configure_axis(
    labelFontSize=16,
    titleFontSize=18
).configure_title(
    fontSize=20
)

# Save to HTML
chart.save("./plots/simple_regression_full_text_data.html")

chart

alt.LayerChart(...)

In [ ]:
# rest of the questions

regression_results_df = pd.read_json("../data/unspun_abstracts/analysis_gpt/importance_answer_simple_regression_summary_all_new.json", orient="index")

# Ensure index is reset and available as a column
regression_results_df.reset_index(inplace=True)
regression_results_df = regression_results_df.rename(columns={'index': 'model_name'})

regression_results_df["model_name_custom"] = regression_results_df["model_name"].map(custom_labels)

# Create the Altair chart
points = alt.Chart(regression_results_df).mark_point(
    filled=True,
    color='red',
    size=50  # Increase point size
).encode(
    x=alt.X('coef:Q').title('Coefficient'),
    y=alt.Y('model_name_custom:N').title('LLM Name').sort(
        field='coef',  # Sort by coefficient values
        order='descending'
    )
).properties(
    width=600,
    height=300
)

# Add error bars
error_bars = points.mark_rule(
    strokeWidth=2  # Increase width of error bars
).encode(
    x='ci_lower:Q',
    x2='ci_upper:Q',
    size=alt.value(2)  # Set the width of error bars
)

# Add vertical line
vertical_line = alt.Chart(pd.DataFrame({'x': [0.640000]})).mark_rule(
    color='blue',
    strokeDash=[4, 4],  # Make it dashed
    strokeWidth=2
).encode(
    x='x:Q',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Add label for vertical line
label = alt.Chart(pd.DataFrame({'x': [0.640000], 'y': [regression_results_df['model_name_custom'].iloc[0]]})).mark_text(
    text='Human Experts',
    align='center',
    dx=5,  # Adjust text position
    dy=-10,
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    y=alt.value(0),  # Adjust position if necessary
    color=alt.value('#0868ac')  # Specify the color directly
)

# Define custom x-axis labels
custom_labels_df = pd.DataFrame({
    'x': [-2.8, 2.2],
    'text': ['Less susceptible to spin', 'More susceptible to spin']
})

# Define custom x-axis labels
left_arrow_df = pd.DataFrame({
    'x': [-4],
    'text': ['←']
})

# Define custom x-axis labels
right_arrow_df = pd.DataFrame({
    'x': [3.8],
    'text': ['→']
})

# Create a text layer for custom x-axis labels
custom_x_labels = alt.Chart(custom_labels_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=24, # adjust horizontal positioning
    fontSize=14,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_left_arrow = alt.Chart(left_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=10, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Create a text layer for custom x-axis labels
custom_x_right_arrow = alt.Chart(right_arrow_df).mark_text(
    align='center',
    baseline='bottom',
    dy=195,  # Adjust vertical positioning
    dx=0, # adjust horizontal positioning
    fontSize=24,
    fontWeight='bold',
).encode(
    x='x:Q',
    text='text:N',
    color=alt.value('#0868ac')  # Specify the color directly
)

# Combine all layers, including the new x-axis labels
chart = alt.layer(error_bars, points, vertical_line, label, custom_x_labels, custom_x_left_arrow, custom_x_right_arrow).configure_axis(
    labelFontSize=16,
    titleFontSize=18
).configure_title(
    fontSize=20
)

# Save to HTML
chart.save("./plots/simple_regression_importance_data.html")

chart

alt.LayerChart(...)

:

#### Binary Spin Detection Results Version

In [174]:
# for model_name in model_names:
#     output_string = ""
#     csv_file_path = f"./eval_outputs/{model_name}/{model_name}_combined_data.csv"
#     data = pd.read_csv(csv_file_path)

#     measures = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer", "overall"]
#     for measure in measures:
#         # get the data for the current measure
#         measure_data = data[data['measure'] == measure]
#         nan_rows_number = measure_data['interpretation_answer'].isnull().sum()
#         # remove rows with NaN values in interpretation_answer
#         measure_data = measure_data.dropna(subset=['interpretation_answer'])

#         # check if there are less than 2 rows
#         if len(measure_data) < 2:
#             continue
        
#         # fit the model
#         model = smf.ols(formula="interpretation_answer ~ is_spin_in_abstract * is_detection_correct", 
#                                     data=measure_data)
#         results = model.fit()

#         output_string += f"Model: {model_name} - {measure}\n"
#         # print number of rows with NaN value(s)
#         output_string += f"Number of rows with NaN value(s) in {model_name}: {nan_rows_number}\n"
#         output_string += results.summary().as_text()
#         output_string += "\n"

#     # save the model summary
#     with open(f"./eval_outputs/{model_name}/{model_name}_regression_binary_summary.txt", "w") as f:
#         f.write(output_string)

In [175]:
# # what the model predicts rather than whether it was correct or not
# for model_name in model_names:
#     output_string = ""
#     csv_file_path = f"./eval_outputs/{model_name}/{model_name}_combined_data.csv"
#     data = pd.read_csv(csv_file_path)

#     measures = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer", "overall"]
#     for measure in measures:
#         # get the data for the current measure
#         measure_data = data[data['measure'] == measure]
#         nan_rows_number = measure_data['interpretation_answer'].isnull().sum()
#         # remove rows with NaN values in interpretation_answer
#         measure_data = measure_data.dropna(subset=['interpretation_answer'])

#         # check if there are less than 2 rows
#         if len(measure_data) < 2:
#             continue
        
#         # fit the model
#         model = smf.ols(formula="interpretation_answer ~ is_spin_in_abstract * detection_model_prediction", 
#                                     data=measure_data)
#         results = model.fit()

#         output_string += f"Model: {model_name} - {measure}\n"
#         # print number of rows with NaN value(s)
#         output_string += f"Number of rows with NaN value(s) in {model_name}: {nan_rows_number}\n"
#         output_string += results.summary().as_text()
#         output_string += "\n"

#     # save the model summary
#     with open(f"./eval_outputs/{model_name}/{model_name}_regression_binary_direct_model_prediction_summary.txt", "w") as f:
#         f.write(output_string)

#### Probability Spin Detection Results Version

In [176]:
# model_names = gpt_models + huggingface_models # remove no token probability models

# for model_name in model_names:
#     output_string = ""
#     csv_file_path = f"./eval_outputs/{model_name}/{model_name}_combined_data.csv"
#     data = pd.read_csv(csv_file_path)

#     measures = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer", "overall"]
#     for measure in measures:
#         # get the data for the current measure
#         measure_data = data[data['measure'] == measure]
#         nan_rows_number = measure_data['interpretation_answer'].isnull().sum()
#         # remove rows with NaN values in interpretation_answer
#         measure_data = measure_data.dropna(subset=['interpretation_answer', 'detection_probability'])
        
#         # if is_detection_no_spin_correct == 1, then detection_probability. Otherwise, 1 - detection_probability
#         measure_data['regression_detection_variable'] = measure_data.apply(lambda x: x['detection_probability'] if x['is_detection_correct'] == 1 else 1 - x['detection_probability'], axis=1)
#         # check if there are less than 2 rows
#         if len(measure_data) < 2:
#             continue

#         # fit the model
#         model = smf.ols(formula="interpretation_answer ~ is_spin_in_abstract * regression_detection_variable",
#                                     data=measure_data)
#         results = model.fit()

#         output_string += f"Model: {model_name} - {measure}\n"
#         # print number of rows with NaN value(s)
#         output_string += f"Number of rows with NaN value(s) in {model_name}: {nan_rows_number}\n"
#         output_string += results.summary().as_text()
#         output_string += "\n"

#     # save the model summary
#     with open(f"./eval_outputs/{model_name}/{model_name}_regression_probability_summary.txt", "w") as f:
#         f.write(output_string)

In [177]:
# # what the model predicts rather than whether it was correct or not

# model_names = gpt_models + huggingface_models # remove no token probability models

# for model_name in model_names:
#     output_string = ""
#     csv_file_path = f"./eval_outputs/{model_name}/{model_name}_combined_data.csv"
#     data = pd.read_csv(csv_file_path)

#     measures = ["benefit_answer", "rigor_answer", "importance_answer", "full_text_answer", "another_trial_answer", "overall"]
#     for measure in measures:
#         # get the data for the current measure
#         measure_data = data[data['measure'] == measure]
#         nan_rows_number = measure_data['interpretation_answer'].isnull().sum()
#         # remove rows with NaN values in interpretation_answer
#         measure_data = measure_data.dropna(subset=['interpretation_answer', 'detection_probability'])
        
#         # if is_detection_no_spin_correct == 1, then detection_probability. Otherwise, 1 - detection_probability
#         measure_data['regression_detection_variable'] = measure_data.apply(lambda x: x['detection_probability'] if x['detection_model_prediction'] == 1 else 1 - x['detection_probability'], axis=1)
#         # check if there are less than 2 rows
#         if len(measure_data) < 2:
#             continue

#         # fit the model
#         model = smf.ols(formula="interpretation_answer ~ is_spin_in_abstract * regression_detection_variable",
#                                     data=measure_data)
#         results = model.fit()

#         output_string += f"Model: {model_name} - {measure}\n"
#         # print number of rows with NaN value(s)
#         output_string += f"Number of rows with NaN value(s) in {model_name}: {nan_rows_number}\n"
#         output_string += results.summary().as_text()
#         output_string += "\n"

#     # save the model summary
#     with open(f"./eval_outputs/{model_name}/{model_name}_regression_probability_direct_model_prediction_summary.txt", "w") as f:
#         f.write(output_string)

## PLS LLM Interpretations

### Average Tokens

In [5]:
# get all model names
model_names = model_metadata.keys()
# remove alpacare-13B
model_names = [x for x in model_names if x != "alpacare-13B"]

len(model_names)

22

In [8]:
# get all PLS outputs from all LLMs
enc = tiktoken.get_encoding("o200k_base") # for gpt-4o and gpt-4o mini

model_token_stats = {}
number_of_tokens_total = [] # for all models
for model_name in model_names:
    csv_file_path = f"./pls_outputs/{model_name}/{model_name}_outputs.csv"
    data = pd.read_csv(csv_file_path)
    # calculate the number of tokens for each row in plain_language_summary
    plain_language_summaries = data['plain_language_summary'].tolist()

    number_of_tokens = []
    for summary in plain_language_summaries:
        token_integers = enc.encode(summary)
        number_of_tokens.append(len(token_integers))
        number_of_tokens_total.append(len(token_integers))

    # average number of tokens
    average_number_of_tokens = np.mean(number_of_tokens)
    # SD of tokens
    sd_number_of_tokens = np.std(number_of_tokens)
    model_token_stats[model_name] = {"average_number_of_tokens": average_number_of_tokens, "sd_number_of_tokens": sd_number_of_tokens}

model_token_stats_df = pd.DataFrame(model_token_stats).T
model_token_stats_df["model_name"] = model_token_stats_df.index

model_token_stats_df

,average_number_of_tokens,sd_number_of_tokens,model_name
alpacare-7B,120.416667,56.264936,alpacare-7B
biomedgpt7B,195.000000,59.498459,biomedgpt7B
biomistral7B,140.766667,73.807941,biomistral7B
claude_3.5-haiku,225.033333,15.084171,claude_3.5-haiku
claude_3.5-sonnet,230.516667,19.185491,claude_3.5-sonnet
gemini_1.5_flash,214.216667,30.953778,gemini_1.5_flash
gemini_1.5_flash-8B,207.700000,37.768285,gemini_1.5_flash-8B
gpt4o,207.850000,44.255254,gpt4o
gpt4o-mini,253.783333,38.084595,gpt4o-mini
gpt35,94.483333,18.754992,gpt35
llama2_chat-7B,230.450000,32.119270,llama2_chat-7B
llama2_chat-13B,225.733333,31.079397,llama2_chat-13B
llama2_chat-70B,227.900000,35.466745,llama2_chat-70B
llama3_instruct-8B,266.533333,27.110556,llama3_instruct-8B
llama3_instruct-70B,248.816667,40.183534,llama3_instruct-70B
med42-8B,172.616667,50.387860,med42-8B
med42-70B,290.533333,12.620706,med42-70B
mistral_instruct7B,150.833333,55.947942,mistral_instruct7B
olmo2_instruct-7B,282.100000,3.176476,olmo2_instruct-7B
olmo2_instruct-13B,272.033333,20.209706,olmo2_instruct-13B
openbiollm-8B,165.566667,71.853408,openbiollm-8B
openbiollm-70B,155.400000,54.012097,openbiollm-70B

In [9]:
# get the average across all
average_number_of_tokens = np.mean(number_of_tokens_total)
sd_number_of_tokens = np.std(number_of_tokens_total)

average_number_of_tokens, sd_number_of_tokens

(np.float64(208.10378787878787), np.float64(67.01472464306116))

In [10]:
# average across all models
average_number_of_tokens = model_token_stats_df["average_number_of_tokens"].mean()
sd_number_of_tokens = model_token_stats_df["sd_number_of_tokens"].mean()

average_number_of_tokens, sd_number_of_tokens

(np.float64(208.10378787878787), np.float64(37.62843632260712))

### LLM Evaluation Results

In [13]:
# the following files were manually created
claude_evaluator_results = pd.read_json("./pls_outputs/extended_dataset/_interpretation_eval_results/claude_3.5-sonnet/claude_3.5-sonnet_pls_interpretation_overall_metrics.json", orient="index")
gpt4o_mini_evaluator_results = pd.read_json("./pls_outputs/extended_dataset/_interpretation_eval_results/gpt4o-mini/gpt4o-mini_pls_interpretation_overall_metrics.json", orient="index")
openbiollm_70b_evaluator_results = pd.read_json("./pls_outputs/extended_dataset/_interpretation_eval_results/openbiollm-70B/openbiollm-70B_pls_interpretation_overall_metrics.json", orient="index")

In [14]:
def calculate_confidence_interval(df, df_column_name):
    mean_diff = df[df_column_name].mean()  # Calculate the mean
    std_dev = df[df_column_name].std()  # Calculate the standard deviation
    n = len(df[df_column_name])  # Sample size

    # Calculate the margin of error for 95% CI (z = 1.96)
    z = 1.96
    margin_of_error = z * (std_dev / sqrt(n))

    # Calculate the 95% Confidence Interval
    ci_lower = mean_diff - margin_of_error
    ci_upper = mean_diff + margin_of_error

    return ci_lower, ci_upper

In [15]:
pls_gpt4o_mini_model_stats_df = calculate_model_stats(gpt4o_mini_evaluator_results, method_name = "GPT-4o Mini")

pls_gpt4o_mini_model_stats_df

   mean_diff  ci_lower  ci_upper                metric       method
0   1.692121  1.574447  1.809795        benefit_answer  GPT-4o Mini
1   0.655455  0.605632  0.705277          rigor_answer  GPT-4o Mini
2   1.135758  1.066447  1.205068     importance_answer  GPT-4o Mini
3   1.536364  1.433524  1.639203      full_text_answer  GPT-4o Mini
4   1.681515  1.566895  1.796136  another_trial_answer  GPT-4o Mini

In [16]:
pls_claude_model_stats_df = calculate_model_stats(claude_evaluator_results, method_name = "Claude 3.5 Sonnet")

pls_claude_model_stats_df

   mean_diff  ci_lower  ci_upper                metric             method
0   0.801802  0.689977  0.913627        benefit_answer  Claude 3.5 Sonnet
1  -0.189411 -0.270355 -0.108467          rigor_answer  Claude 3.5 Sonnet
2   0.226097  0.145219  0.306976     importance_answer  Claude 3.5 Sonnet
3   0.663469  0.519308  0.807630      full_text_answer  Claude 3.5 Sonnet
4   1.104029  1.008814  1.199244  another_trial_answer  Claude 3.5 Sonnet

In [17]:
pls_openbiollm_model_stats_df = calculate_model_stats(openbiollm_70b_evaluator_results, method_name = "OpenBioLLM 70B")

pls_openbiollm_model_stats_df

   mean_diff  ci_lower  ci_upper                metric          method
0   1.699963  1.559266  1.840660        benefit_answer  OpenBioLLM 70B
1   0.101372  0.067478  0.135266          rigor_answer  OpenBioLLM 70B
2   0.800792  0.704386  0.897198     importance_answer  OpenBioLLM 70B
3   0.166671  0.059299  0.274043      full_text_answer  OpenBioLLM 70B
4   1.475031  1.287530  1.662533  another_trial_answer  OpenBioLLM 70B

In [18]:
# combine two dataframes
all_pls_model_stats_df = pd.concat([pls_gpt4o_mini_model_stats_df, pls_claude_model_stats_df, pls_openbiollm_model_stats_df], ignore_index=True)

all_pls_model_stats_df

    mean_diff  ci_lower  ci_upper                metric             method
0    1.692121  1.574447  1.809795        benefit_answer        GPT-4o Mini
1    0.655455  0.605632  0.705277          rigor_answer        GPT-4o Mini
2    1.135758  1.066447  1.205068     importance_answer        GPT-4o Mini
3    1.536364  1.433524  1.639203      full_text_answer        GPT-4o Mini
4    1.681515  1.566895  1.796136  another_trial_answer        GPT-4o Mini
5    0.801802  0.689977  0.913627        benefit_answer  Claude 3.5 Sonnet
6   -0.189411 -0.270355 -0.108467          rigor_answer  Claude 3.5 Sonnet
7    0.226097  0.145219  0.306976     importance_answer  Claude 3.5 Sonnet
8    0.663469  0.519308  0.807630      full_text_answer  Claude 3.5 Sonnet
9    1.104029  1.008814  1.199244  another_trial_answer  Claude 3.5 Sonnet
10   1.699963  1.559266  1.840660        benefit_answer     OpenBioLLM 70B
11   0.101372  0.067478  0.135266          rigor_answer     OpenBioLLM 70B
12   0.800792  0.704386  0.897198     importance_answer     OpenBioLLM 70B
13   0.166671  0.059299  0.274043      full_text_answer     OpenBioLLM 70B
14   1.475031  1.287530  1.662533  another_trial_answer     OpenBioLLM 70B

In [ ]:
# create altair grouped barchart
# grouped by metric and evaluator

# Create a mapping for custom facet titles
facet_title_mapping = {
    'benefit_answer': 'Benefit',
    'rigor_answer': 'Rigor',
    'importance_answer': 'Importance',
    'full_text_answer': 'Full-Text',
    'another_trial_answer': 'Another Trial'
}

# Define the desired order for the facets
facet_order = ['Benefit', 'Rigor', 'Importance', 'Full-Text', 'Another Trial']

color_mapping = {
    'Claude 3.5 Sonnet': '#0868ac',  
    'GPT-4o Mini': '#43a2ca',  
    'OpenBioLLM 70B': '#7bccc4'
}

method_order = ['Claude 3.5 Sonnet', 'GPT-4o Mini', 'OpenBioLLM 70B']

# Apply the mapping as a calculated field
chart_data = all_pls_model_stats_df.copy()
chart_data['metric'] = chart_data['metric'].map(facet_title_mapping)

# Configure global font sizes
chart_config = {
    "axis": {"labelFontSize": 20, "titleFontSize": 22},  # Axis labels and titles
    "header": {"labelFontSize": 20, "titleFontSize": 22},  # Facet headers
    "legend": {"labelFontSize": 18, "titleFontSize": 20},  # Legend labels and titles
    "text": {"fontSize": 20},  # Text mark size
}

# Bar chart
bars = alt.Chart(chart_data).mark_bar().encode(
    x=alt.X('method:N', title=None, axis=alt.Axis(labelAngle=-45), sort = method_order),
    y=alt.Y('mean_diff:Q', title='Mean Difference'),
    color=alt.Color('method:N', title='Evaluator', legend=None, scale=alt.Scale(domain=list(color_mapping.keys()), range=list(color_mapping.values())))
).properties(
    width=120,  # Set the width to 300 pixels
    height=250  # Set the height to 300 pixels
)

# Error bars
error_bars = alt.Chart(chart_data).mark_errorbar().encode(
    alt.X("method:N", sort = method_order),
    alt.Y("ci_lower:Q").title("Mean Difference"),
    alt.Y2("ci_upper:Q"),
    strokeWidth=alt.value(2),
    color=alt.value('gray')
)

# Add value labels
text = bars.mark_text(
    align='center',
    baseline='bottom',
    fontWeight='bold',
    dy=alt.expr(expr=alt.expr.if_(alt.datum.mean_diff >= 0, -1, 20))  # Adjust the position of the text    
).encode(
    text=alt.Text('mean_diff:Q', format='.2f'),
    color=alt.value('black')  # Set text color to black
)

# Combine layers and facet
chart = alt.layer(bars, text, error_bars, data=chart_data).facet(
    column=alt.Column('metric:N', title=None, sort=facet_order),
).configure(**chart_config)  # Apply

# save to html
chart.save("./plots/pls_evaluator_comparison_by_measures.html")

chart

alt.FacetChart(...)

: